import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: "#FAF8F5",
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  header: {
    backgroundColor: "#3A3330",
    paddingBottom: 30,
    paddingHorizontal: 19,
    paddingTop: 38,
  },
  brand: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 10,
    letterSpacing: 1,
  },
  title: {
    color: "#FFFFFF",
    fontFamily: "serif",
    fontSize: 31,
    marginTop: 4,
  },
  profileRow: {
    alignItems: "center",
    flexDirection: "row",
    marginTop: 18,
  },
  avatar: {
    alignItems: "center",
    backgroundColor: "#C9A86A",
    borderRadius: 30,
    height: 60,
    justifyContent: "center",
    width: 60,
  },
  avatarText: {
    color: "#FFFFFF",
    fontFamily: "serif",
    fontSize: 19,
  },
  profileCopy: {
    flex: 1,
    marginLeft: 15,
    minWidth: 0,
  },
  name: {
    color: "#FFFFFF",
    fontFamily: "serif",
    fontSize: 25,
  },
  role: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 11,
    marginTop: 2,
  },
  statusChip: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(201,168,106,0.2)",
    borderColor: "rgba(201,168,106,0.3)",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 4,
    marginTop: 7,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  statusDot: {
    backgroundColor: "#C9A86A",
    borderRadius: 3,
    height: 6,
    width: 6,
  },
  statusText: {
    color: "#C9A86A",
    fontSize: 10,
    letterSpacing: 0.25,
  },
  content: {
    paddingHorizontal: 19,
    paddingTop: 19,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(60,51,48,0.05)",
    borderRadius: 15,
    borderWidth: 1,
    padding: 16,
  },
  mt15: {
    marginTop: 15,
  },
  cardLabel: {
    color: "#7A6F68",
    fontSize: 10,
    fontWeight: "600",
    letterSpacing: 1,
    marginBottom: 4,
  },
  contactRow: {
    alignItems: "center",
    flexDirection: "row",
    marginTop: 12,
  },
  contactRowLast: {
    marginBottom: 0,
  },
  iconWrap: {
    alignItems: "center",
    backgroundColor: "#F5F2ED",
    borderRadius: 11,
    height: 30,
    justifyContent: "center",
    width: 30,
  },
  contactCopy: {
    flex: 1,
    marginLeft: 11,
    minWidth: 0,
  },
  contactText: {
    color: "#2C2420",
    fontSize: 13,
  },
  contactMeta: {
    color: "#8A7E76",
    fontSize: 11,
    marginTop: 2,
  },
  summaryRow: {
    flexDirection: "row",
    gap: 11,
    marginTop: 12,
  },
  summaryBox: {
    alignItems: "center",
    backgroundColor: "#F7F3ED",
    borderRadius: 15,
    flex: 1,
    justifyContent: "center",
    minHeight: 72,
    paddingHorizontal: 10,
    paddingVertical: 14,
  },
  summaryValue: {
    color: "#2C2420",
    fontFamily: "serif",
    fontSize: 20,
    lineHeight: 24,
    textAlign: "center",
  },
  summaryLabel: {
    color: "#8A7E76",
    fontSize: 10,
    fontWeight: "600",
    letterSpacing: 0.4,
    marginTop: 6,
    textAlign: "center",
  },
  settingsCard: {
    overflow: "hidden",
    padding: 0,
  },
  settingRow: {
    alignItems: "center",
    flexDirection: "row",
    paddingHorizontal: 15,
    paddingVertical: 14,
  },
  settingDivider: {
    borderBottomColor: "rgba(60,51,48,0.05)",
    borderBottomWidth: 1,
  },
  settingTextWrap: {
    flex: 1,
    marginHorizontal: 11,
    minWidth: 0,
  },
  settingTitle: {
    color: "#2C2420",
    fontSize: 13,
    fontWeight: "600",
  },
  settingSubtitle: {
    color: "#7A6F68",
    fontSize: 11,
    marginTop: 2,
  },
  signOutCard: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#FFC9C9",
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: "row",
    paddingHorizontal: 15,
    paddingVertical: 13,
  },
  signOutIconWrap: {
    alignItems: "center",
    backgroundColor: "#FEF2F2",
    borderRadius: 11,
    height: 30,
    justifyContent: "center",
    width: 30,
  },
  signOutCopy: {
    flex: 1,
    marginLeft: 11,
    minWidth: 0,
  },
  signOutTitle: {
    color: "#FB2C36",
    fontSize: 13,
    fontWeight: "500",
  },
  signOutSub: {
    color: "rgba(255,100,103,0.7)",
    fontSize: 11,
    fontWeight: "500",
    marginTop: 1,
  },
  versionText: {
    color: "rgba(122,111,104,0.4)",
    fontSize: 10,
    letterSpacing: 1,
    marginTop: 15,
    textAlign: "center",
  },
});
