import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: "#FAF8F5",
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  header: {
    backgroundColor: "#3A3330",
    paddingHorizontal: 19,
    paddingTop: 38,
    paddingBottom: 30,
  },
  brand: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 10,
    letterSpacing: 1,
  },
  title: {
    color: "#FFFFFF",
    fontFamily: "serif",
    fontSize: 31,
    marginTop: 4,
  },
  profileRow: {
    alignItems: "center",
    flexDirection: "row",
    marginTop: 18,
  },
  avatar: {
    alignItems: "center",
    backgroundColor: "#C9A86A",
    borderRadius: 30,
    height: 60,
    justifyContent: "center",
    width: 60,
  },
  avatarText: {
    color: "#FFFFFF",
    fontFamily: "serif",
    fontSize: 19,
  },
  name: {
    color: "#FFFFFF",
    fontFamily: "serif",
    fontSize: 25,
    marginLeft: 15,
  },
  role: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 11,
    marginLeft: 15,
    marginTop: 2,
  },
  statusChip: {
    alignItems: "center",
    backgroundColor: "rgba(201,168,106,0.2)",
    borderColor: "rgba(201,168,106,0.3)",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 4,
    marginLeft: 15,
    marginTop: 7,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  statusDot: {
    backgroundColor: "#C9A86A",
    borderRadius: 3,
    height: 6,
    width: 6,
  },
  statusText: {
    color: "#C9A86A",
    fontSize: 10,
    letterSpacing: 0.25,
  },
  content: {
    paddingHorizontal: 19,
    paddingTop: 19,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(60,51,48,0.05)",
    borderRadius: 15,
    borderWidth: 1,
    padding: 16,
  },
  mt15: {
    marginTop: 15,
  },
  cardLabel: {
    color: "#7A6F68",
    fontSize: 10,
    letterSpacing: 1,
  },
  contactRow: {
    alignItems: "center",
    flexDirection: "row",
    marginTop: 11,
  },
  iconWrap: {
    alignItems: "center",
    backgroundColor: "#F5F2ED",
    borderRadius: 11,
    height: 30,
    justifyContent: "center",
    width: 30,
  },
  contactText: {
    color: "#2C2420",
    fontSize: 13,
    marginLeft: 11,
  },
  summaryRow: {
    flexDirection: "row",
    gap: 11,
    marginTop: 11,
  },
  summaryBox: {
    alignItems: "center",
    backgroundColor: "rgba(245,242,237,0.6)",
    borderRadius: 15,
    flex: 1,
    paddingVertical: 9,
  },
  summaryValue: {
    color: "#2C2420",
    fontFamily: "serif",
    fontSize: 17,
  },
  summaryLabel: {
    color: "#7A6F68",
    fontSize: 10,
    letterSpacing: 0.25,
    marginTop: 2,
  },
  settingsCard: {
    overflow: "hidden",
    padding: 0,
  },
  settingRow: {
    alignItems: "center",
    flexDirection: "row",
    paddingHorizontal: 15,
    paddingVertical: 13,
  },
  settingDivider: {
    borderBottomColor: "rgba(60,51,48,0.05)",
    borderBottomWidth: 1,
  },
  settingTextWrap: {
    flex: 1,
    marginHorizontal: 11,
  },
  settingTitle: {
    color: "#2C2420",
    fontSize: 13,
  },
  settingSubtitle: {
    color: "#7A6F68",
    fontSize: 11,
    marginTop: 1,
  },
  signOutCard: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#FFC9C9",
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: "row",
    paddingHorizontal: 15,
    paddingVertical: 13,
  },
  signOutIconWrap: {
    alignItems: "center",
    backgroundColor: "#FEF2F2",
    borderRadius: 11,
    height: 30,
    justifyContent: "center",
    width: 30,
  },
  signOutTitle: {
    color: "#FB2C36",
    fontSize: 13,
    fontWeight: "500",
    marginLeft: 11,
  },
  signOutSub: {
    color: "rgba(255,100,103,0.7)",
    fontSize: 11,
    fontWeight: "500",
    marginLeft: 11,
    marginTop: 1,
  },
  versionText: {
    color: "rgba(122,111,104,0.4)",
    fontSize: 10,
    letterSpacing: 1,
    marginTop: 15,
    textAlign: "center",
  },
  bottomNav: {
    backgroundColor: "rgba(255,255,255,0.95)",
    borderTopColor: "rgba(60,51,48,0.08)",
    borderTopWidth: 1,
    bottom: 0,
    flexDirection: "row",
    height: 74,
    left: 0,
    position: "absolute",
    right: 0,
  },
  bottomItem: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
  },
  bottomIconWrap: {
    position: "relative",
  },
  bottomBadge: {
    alignItems: "center",
    backgroundColor: "#C9A86A",
    borderRadius: 8,
    height: 15,
    justifyContent: "center",
    minWidth: 15,
    paddingHorizontal: 4,
    position: "absolute",
    right: -10,
    top: -5,
  },
  bottomBadgeText: {
    color: "#FFFFFF",
    fontSize: 9,
  },
  bottomLabel: {
    color: "rgba(122,111,104,0.7)",
    fontSize: 10,
    marginTop: 4,
  },
  bottomLabelActive: {
    color: "#C9A86A",
  },
  bottomActiveIndicator: {
    backgroundColor: "#C9A86A",
    borderRadius: 999,
    height: 2,
    position: "absolute",
    top: 6,
    width: 20,
  },
});
