import { Platform, StyleSheet } from "react-native";

const GOLD = "#C9A86A";
const GOLD_DEEP = "#B89558";
const INK = "#2C2420";
const CHARCOAL = "#3A3330";
const MUTED = "#8A7E76";
const SOFT = "#B8ACA3";
const CREAM = "#FAF8F5";
const PAPER = "#FFFFFF";

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: CREAM,
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },

  /* ——— Header ——— */
  headerWrap: {
    backgroundColor: GOLD_DEEP,
    overflow: "hidden",
    paddingBottom: 42,
    paddingHorizontal: 24,
    position: "relative",
  },
  headerDecorLarge: {
    backgroundColor: "rgba(255,255,255,0.07)",
    borderRadius: 999,
    height: 210,
    position: "absolute",
    right: -70,
    top: -60,
    width: 210,
  },
  headerDecorMedium: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 999,
    height: 120,
    position: "absolute",
    right: 40,
    top: -30,
    width: 120,
  },
  headerDecorSmall: {
    backgroundColor: "rgba(255,255,255,0.045)",
    borderRadius: 999,
    bottom: 18,
    height: 88,
    left: -36,
    position: "absolute",
    width: 88,
  },
  headerTopRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
    zIndex: 1,
  },
  headerIntro: {
    flex: 1,
    paddingRight: 14,
  },
  brandMark: {
    color: "rgba(255,255,255,0.55)",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 2.4,
    marginBottom: 14,
  },
  greetingLabel: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 1.6,
  },
  userName: {
    color: PAPER,
    fontFamily: "serif",
    fontSize: 32,
    letterSpacing: -0.4,
    lineHeight: 38,
    marginTop: 6,
  },
  headerSubtitle: {
    color: "rgba(255,255,255,0.58)",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 6,
    maxWidth: 240,
  },
  notifyWrap: {
    marginTop: 2,
    position: "relative",
  },
  notifyPressed: {
    opacity: 0.85,
  },
  notifyIcon: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.16)",
    borderColor: "rgba(255,255,255,0.18)",
    borderRadius: 18,
    borderWidth: 1,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  notifyBadge: {
    alignItems: "center",
    backgroundColor: "#D64545",
    borderColor: GOLD_DEEP,
    borderRadius: 9,
    borderWidth: 2,
    height: 18,
    justifyContent: "center",
    minWidth: 18,
    paddingHorizontal: 4,
    position: "absolute",
    right: -4,
    top: -5,
  },
  notifyBadgeText: {
    color: PAPER,
    fontSize: 9,
    fontWeight: "700",
  },
  activeProjectRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    marginTop: 22,
    zIndex: 1,
  },
  line: {
    backgroundColor: "rgba(255,255,255,0.18)",
    flex: 1,
    height: StyleSheet.hairlineWidth,
  },
  activeProjectPill: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 999,
    flexDirection: "row",
    gap: 7,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  activeProjectDot: {
    backgroundColor: PAPER,
    borderRadius: 3,
    height: 5,
    width: 5,
  },
  activeProjectText: {
    color: "rgba(255,255,255,0.82)",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.3,
  },

  /* ——— Project card ——— */
  projectCard: {
    alignSelf: "center",
    backgroundColor: PAPER,
    borderColor: "rgba(44,36,32,0.05)",
    borderRadius: 22,
    borderWidth: 1,
    marginTop: -26,
    overflow: "hidden",
    shadowColor: "#1C1612",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    width: "90%",
    zIndex: 2,
    ...Platform.select({
      android: { elevation: 7 },
    }),
  },
  projectCardAccent: {
    backgroundColor: GOLD,
    height: 4,
  },
  projectCardBody: {
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  projectStateBody: {
    alignItems: "center",
    gap: 10,
    justifyContent: "center",
    minHeight: 156,
    paddingHorizontal: 12,
  },
  projectStateTitle: {
    color: INK,
    fontFamily: "serif",
    fontSize: 18,
  },
  projectStateText: {
    color: MUTED,
    fontSize: 13,
    lineHeight: 20,
    textAlign: "center",
  },
  projectStateHint: {
    color: SOFT,
    fontSize: 12,
    marginTop: 2,
  },
  projectHead: {
    gap: 0,
  },
  projectTitle: {
    color: INK,
    fontFamily: "serif",
    fontSize: 26,
    letterSpacing: -0.3,
    lineHeight: 30,
  },
  projectCode: {
    color: SOFT,
    fontSize: 12,
    letterSpacing: 0.2,
    marginTop: 4,
  },
  statusBadge: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(201,168,106,0.12)",
    borderColor: "rgba(201,168,106,0.35)",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    marginTop: 10,
    maxWidth: "100%",
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  statusDot: {
    backgroundColor: GOLD,
    borderRadius: 3,
    flexShrink: 0,
    height: 6,
    width: 6,
  },
  statusText: {
    color: "#8A6E3A",
    flexShrink: 1,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.1,
  },
  peopleRow: {
    alignItems: "center",
    backgroundColor: "#FBF9F6",
    borderColor: "rgba(44,36,32,0.04)",
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    marginTop: 16,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  avatarRow: {
    flexDirection: "row",
    marginRight: 12,
  },
  avatarCircle: {
    alignItems: "center",
    borderColor: PAPER,
    borderRadius: 15,
    borderWidth: 2,
    height: 30,
    justifyContent: "center",
    width: 30,
  },
  avatarDark: {
    backgroundColor: CHARCOAL,
  },
  avatarGold: {
    backgroundColor: GOLD,
  },
  avatarMuted: {
    backgroundColor: "#E8E2DA",
  },
  avatarOverlap: {
    marginLeft: -8,
  },
  avatarText: {
    color: PAPER,
    fontSize: 9,
    fontWeight: "700",
  },
  avatarTextMuted: {
    color: MUTED,
    fontSize: 11,
    fontWeight: "600",
  },
  peopleCopy: {
    flex: 1,
    minWidth: 0,
  },
  peopleName: {
    color: INK,
    fontSize: 13,
    fontWeight: "600",
  },
  peopleRole: {
    color: MUTED,
    fontSize: 11,
    marginTop: 2,
  },
  stageCard: {
    backgroundColor: "#F5F1EA",
    borderRadius: 16,
    marginTop: 14,
    paddingHorizontal: 15,
    paddingVertical: 13,
  },
  stageTopRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  stageLabel: {
    color: MUTED,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.15,
  },
  stageDate: {
    color: SOFT,
    fontSize: 10,
  },
  stageTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    marginTop: 8,
  },
  stageDot: {
    backgroundColor: GOLD,
    borderRadius: 4,
    height: 8,
    marginRight: 9,
    width: 8,
  },
  stageTitle: {
    color: INK,
    fontFamily: "serif",
    fontSize: 15,
  },
  projectButton: {
    alignItems: "center",
    backgroundColor: CHARCOAL,
    borderRadius: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 16,
    paddingLeft: 18,
    paddingRight: 8,
    paddingVertical: 8,
  },
  projectButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.992 }],
  },
  projectButtonText: {
    color: PAPER,
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 0.1,
  },
  projectButtonIcon: {
    alignItems: "center",
    backgroundColor: GOLD,
    borderRadius: 12,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  newProjectButton: {
    alignItems: "center",
    backgroundColor: "rgba(201,168,106,0.08)",
    borderColor: "rgba(201,168,106,0.35)",
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 10,
    paddingVertical: 12,
  },
  newProjectButtonPressed: {
    opacity: 0.88,
  },
  newProjectButtonText: {
    color: GOLD_DEEP,
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 0.1,
  },
  switchProjectButton: {
    alignItems: "center",
    backgroundColor: PAPER,
    borderColor: "rgba(184,149,88,0.35)",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    justifyContent: "center",
    marginTop: 10,
    paddingVertical: 11,
  },
  switchProjectButtonPressed: {
    opacity: 0.88,
  },
  switchProjectButtonText: {
    color: GOLD_DEEP,
    fontSize: 13,
    fontWeight: "600",
  },

  /* ——— Updates ——— */
  updateSection: {
    marginTop: 6,
    paddingBottom: 10,
    paddingHorizontal: 20,
  },
  updateHeader: {
    alignItems: "flex-end",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 14,
    marginTop: 24,
  },
  updateHeaderCopy: {
    flex: 1,
    paddingRight: 12,
  },
  updateTitle: {
    color: INK,
    fontFamily: "serif",
    fontSize: 20,
    letterSpacing: -0.2,
  },
  updateSubtitle: {
    color: MUTED,
    fontSize: 12,
    marginTop: 3,
  },
  seeAllButton: {
    alignItems: "center",
    backgroundColor: "rgba(201,168,106,0.12)",
    borderRadius: 999,
    flexDirection: "row",
    gap: 2,
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  seeAllPressed: {
    opacity: 0.8,
  },
  seeAllText: {
    color: "#A8894E",
    fontSize: 11,
    fontWeight: "700",
  },
  updateList: {
    gap: 0,
  },
  updateCard: {
    backgroundColor: PAPER,
    borderColor: "rgba(44,36,32,0.05)",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    marginBottom: 10,
    overflow: "hidden",
    paddingRight: 14,
    paddingVertical: 14,
  },
  updateCardLast: {
    marginBottom: 0,
  },
  updateCardPrimary: {
    backgroundColor: "#FFFCF7",
    borderColor: "rgba(201,168,106,0.28)",
  },
  updateCardPressed: {
    opacity: 0.92,
  },
  updateRail: {
    borderRadius: 2,
    marginRight: 12,
    marginVertical: 2,
    width: 3,
  },
  updateRailPrimary: {
    backgroundColor: GOLD,
  },
  updateRailNeutral: {
    backgroundColor: "#DDD5CB",
  },
  updateBody: {
    flex: 1,
    minWidth: 0,
  },
  updateTitleRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
  },
  updateCardTitle: {
    color: INK,
    flex: 1,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
  },
  updateTime: {
    color: SOFT,
    fontSize: 10,
    fontWeight: "500",
    marginTop: 2,
  },
  updateCardDescription: {
    color: MUTED,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 4,
  },
});
