import { StyleSheet } from "react-native";
import { SALE } from "../../sale/styles/sale.styles";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: SALE.bg },
  header: {
    backgroundColor: SALE.charcoal,
    paddingHorizontal: 19,
    paddingBottom: 14,
    gap: 12,
  },
  headerTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  headerCopy: { flex: 1, minWidth: 0 },
  headerEyebrow: {
    color: "rgba(255,255,255,0.55)",
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  headerTitle: {
    color: SALE.white,
    fontFamily: "serif",
    fontSize: 26,
    fontWeight: "600",
    marginTop: 2,
  },
  headerActions: {
    alignItems: "flex-end",
    gap: 8,
  },
  markAllButton: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  markAllText: {
    color: SALE.white,
    fontSize: 10,
    fontWeight: "600",
  },
  newBadge: {
    backgroundColor: "rgba(201,168,106,0.22)",
    borderColor: "rgba(201,168,106,0.35)",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  newText: {
    color: "#DCC89A",
    fontSize: 10,
    fontWeight: "600",
  },
  filterRow: {
    flexDirection: "row",
    gap: 8,
    paddingRight: 8,
  },
  filterChip: {
    backgroundColor: "rgba(255,255,255,0.1)",
    borderColor: "rgba(255,255,255,0.08)",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  filterChipActive: {
    backgroundColor: SALE.gold,
    borderColor: SALE.gold,
  },
  filterChipText: {
    color: "rgba(255,255,255,0.65)",
    fontSize: 10,
    fontWeight: "500",
  },
  filterChipTextActive: {
    color: SALE.white,
    fontWeight: "700",
  },
  body: { flex: 1 },
  content: {
    paddingHorizontal: 19,
    paddingTop: 14,
  },
  listMetaRow: { marginBottom: 10 },
  listMetaText: {
    color: "rgba(122,111,104,0.75)",
    fontSize: 10,
    letterSpacing: 0.3,
  },
  swipeArea: { minHeight: 280 },
  centerState: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 180,
    paddingHorizontal: 24,
    gap: 10,
  },
  emptyText: {
    color: SALE.muted,
    fontSize: 13,
    textAlign: "center",
    lineHeight: 18,
  },
  retryButton: {
    backgroundColor: SALE.pale,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  retryText: {
    color: SALE.ink,
    fontSize: 12,
    fontWeight: "600",
  },
  card: {
    backgroundColor: SALE.white,
    borderColor: SALE.border,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    marginBottom: 10,
    overflow: "hidden",
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  cardUnread: {
    backgroundColor: "#FFFcf7",
    borderColor: "rgba(201,168,106,0.35)",
  },
  cardUnreadAccent: {
    backgroundColor: SALE.gold,
    bottom: 0,
    left: 0,
    position: "absolute",
    top: 0,
    width: 3,
  },
  cardIconWrap: {
    alignItems: "center",
    borderRadius: 12,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  cardContent: { flex: 1, minWidth: 0 },
  cardTitleRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 8,
    justifyContent: "space-between",
  },
  cardTitle: {
    color: SALE.ink,
    flex: 1,
    fontSize: 13,
    fontWeight: "500",
    lineHeight: 18,
  },
  cardTitleUnread: { fontWeight: "700" },
  categoryBadge: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  categoryBadgeText: {
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  cardProjectLabel: {
    color: SALE.charcoal,
    fontSize: 11,
    fontWeight: "600",
    marginTop: 4,
  },
  cardDescription: {
    color: SALE.muted,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 4,
  },
  cardTime: {
    color: "rgba(122,111,104,0.55)",
    fontSize: 10,
    letterSpacing: 0.3,
    marginTop: 8,
  },
  cardNavigatingIndicator: { marginTop: 6 },
  unreadDot: {
    backgroundColor: SALE.gold,
    borderRadius: 4,
    height: 7,
    marginTop: 6,
    width: 7,
  },
  paginationBar: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
    marginTop: 8,
    marginBottom: 8,
  },
  paginationButton: {
    backgroundColor: SALE.pale,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  paginationButtonDisabled: { opacity: 0.4 },
  paginationButtonText: {
    color: SALE.ink,
    fontSize: 11,
    fontWeight: "600",
  },
  paginationLabel: {
    color: SALE.muted,
    fontSize: 11,
  },
});
