import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  card: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(58,51,48,0.08)",
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 14,
    padding: 16,
  },
  headerRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  cardLabel: {
    color: "#7A6F68",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.7,
  },
  reportButton: {
    backgroundColor: "rgba(201,168,106,0.14)",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  reportButtonDisabled: {
    opacity: 0.45,
  },
  reportButtonText: {
    color: "#8A6D3B",
    fontSize: 11,
    fontWeight: "700",
  },
  scopeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  scopeChip: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(58,51,48,0.12)",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  scopeChipActive: {
    backgroundColor: "#3A3330",
    borderColor: "#3A3330",
  },
  scopeChipText: {
    color: "#7A6F68",
    fontSize: 11,
    fontWeight: "600",
  },
  scopeChipTextActive: {
    color: "#FFFFFF",
  },
  hintText: {
    color: "#7A6F68",
    fontSize: 12,
    lineHeight: 18,
  },
  issueRow: {
    borderColor: "rgba(58,51,48,0.08)",
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  issueTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  issueTitle: {
    color: "#2C2420",
    flex: 1,
    fontSize: 14,
    fontWeight: "700",
  },
  issueMeta: {
    color: "#7A6F68",
    fontSize: 11,
    marginTop: 3,
  },
  badge: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  badgeAtRisk: {
    backgroundColor: "rgba(217,119,6,0.14)",
  },
  badgeOverdue: {
    backgroundColor: "rgba(220,38,38,0.12)",
  },
  badgeText: {
    fontSize: 10,
    fontWeight: "700",
  },
  badgeTextAtRisk: {
    color: "#B45309",
  },
  badgeTextOverdue: {
    color: "#DC2626",
  },
  modalBackdrop: {
    backgroundColor: "rgba(26,22,20,0.45)",
    flex: 1,
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: "#FAF8F5",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "92%",
    paddingBottom: 24,
    paddingHorizontal: 18,
    paddingTop: 16,
  },
  modalHandle: {
    alignSelf: "center",
    backgroundColor: "rgba(58,51,48,0.18)",
    borderRadius: 999,
    height: 4,
    marginBottom: 14,
    width: 42,
  },
  modalHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  modalTitle: {
    color: "#2C2420",
    flex: 1,
    fontFamily: "serif",
    fontSize: 22,
    marginRight: 12,
  },
  closeButton: {
    alignItems: "center",
    backgroundColor: "rgba(58,51,48,0.08)",
    borderRadius: 999,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  fieldLabel: {
    color: "#7A6F68",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.3,
    marginBottom: 7,
    marginTop: 12,
  },
  typeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  typeChip: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(58,51,48,0.12)",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  typeChipActive: {
    backgroundColor: "#3A3330",
    borderColor: "#3A3330",
  },
  typeChipText: {
    color: "#7A6F68",
    fontSize: 11,
    fontWeight: "600",
  },
  typeChipTextActive: {
    color: "#FFFFFF",
  },
  input: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(58,51,48,0.12)",
    borderRadius: 12,
    borderWidth: 1,
    color: "#2C2420",
    fontSize: 14,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  textArea: {
    minHeight: 96,
    textAlignVertical: "top",
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "#3A3330",
    borderRadius: 14,
    marginTop: 16,
    paddingVertical: 13,
  },
  primaryButtonDisabled: {
    opacity: 0.65,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  errorText: {
    color: "#DC2626",
    fontSize: 12,
    marginTop: 10,
  },
  detailBlock: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(58,51,48,0.08)",
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 10,
    padding: 14,
  },
  detailLabel: {
    color: "#7A6F68",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  detailValue: {
    color: "#2C2420",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
});
