export const endpoints = {
  auth: {
    login: "/auth/login",
    refresh: "/auth/refresh",
    me: "/auth/me",
    changePassword: "/auth/me/password",
    logout: "/auth/logout",
  },
  notifications: {
    list: "/notifications/me",
    unreadCount: "/notifications/me/unread-count",
    markRead: (notificationId: string) => `/notifications/${notificationId}/read`,
    markAllRead: "/notifications/me/read-all",
  },
  chat: {
    listByProject: (projectId: string) => `/projects/${projectId}/chats`,
    messages: (chatId: string) => `/project-chats/${chatId}/messages`,
    sendMessage: (chatId: string) => `/project-chats/${chatId}/messages`,
    sendFile: (chatId: string) => `/project-chats/${chatId}/messages/files`,
    search: (projectId: string) => `/projects/${projectId}/chat-messages/search`,
  },
  projects: {
    list: "/projects",
    create: "/projects",
    byUser: (userId: string) => `/projects/by-user/${userId}`,
    detail: (projectId: string) => `/projects/${projectId}`,
    publishedProposal: (projectId: string) => `/projects/${projectId}/published-proposal`,
    phaseDeadlines: (projectId: string) => `/projects/${projectId}/phase-deadlines`,
    updateBasicInfo: (projectId: string) => `/projects/${projectId}/basic-information`,
    updateTargetDate: (projectId: string) => `/projects/${projectId}/target-completion-date`,
    reopenProposal: (projectId: string) => `/projects/${projectId}/reopen-proposal`,
    orders: (projectId: string) => `/projects/${projectId}/orders`,
    proposals: (projectId: string) => `/projects/${projectId}/proposals`,
    quotations: (projectId: string) => `/projects/${projectId}/quotations`,
  },
  proposals: {
    detail: (proposalId: string) => `/proposals/${proposalId}`,
    scenes: (proposalId: string) => `/proposals/${proposalId}/scenes`,
    items: (proposalId: string) => `/proposals/${proposalId}/items`,
    selectFinal: (proposalId: string) => `/proposals/${proposalId}/select-final`,
    requestRevision: (proposalId: string) => `/proposals/${proposalId}/request-revision`,
  },
  quotations: {
    detail: (quotationId: string) => `/quotations/${quotationId}`,
    accept: (quotationId: string) => `/quotations/${quotationId}/accept`,
    requestRevision: (quotationId: string) => `/quotations/${quotationId}/request-revision`,
    reject: (quotationId: string) => `/quotations/${quotationId}/reject`,
  },
  orders: {
    detail: (orderId: string) => `/orders/${orderId}`,
    createDeposit: (orderId: string) => `/orders/${orderId}/payments/deposit`,
    confirmDelivery: (orderId: string) => `/orders/${orderId}/confirm-delivery`,
  },
  projectSchedules: {
    list: "/project-schedules",
    detail: (scheduleId: string) => `/project-schedules/${scheduleId}`,
    updateStatus: (scheduleId: string) => `/project-schedules/${scheduleId}/status`,
  },
  payments: {
    list: "/api/payments",
    detail: (paymentId: string) => `/api/payments/${paymentId}`,
    statusByCode: (paymentCode: string) => `/api/payments/code/${paymentCode}/status`,
    createTransaction: (paymentId: string) => `/api/payments/${paymentId}/transactions`,
    activeTransaction: (paymentId: string) => `/api/payments/${paymentId}/transactions/active`,
    cancelTransaction: (paymentId: string, transactionId: string) =>
      `/api/payments/${paymentId}/transactions/${transactionId}/cancel`,
    payOsPaymentLink: (paymentId: string) => `/api/payments/${paymentId}/payos/payment-link`,
  },
} as const;
