import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  card: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(58,51,48,0.08)",
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 14,
    padding: 16,
  },
  headerRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
    marginBottom: 10,
  },
  headerTextWrap: {
    flex: 1,
    paddingRight: 4,
  },
  cardLabel: {
    color: "#7A6F68",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.7,
  },
  headerHint: {
    color: "#9B8F86",
    fontSize: 11,
    lineHeight: 16,
    marginTop: 4,
  },
  reportButton: {
    backgroundColor: "rgba(201,168,106,0.14)",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  reportButtonDisabled: {
    opacity: 0.45,
  },
  reportButtonText: {
    color: "#8A6D3B",
    fontSize: 11,
    fontWeight: "700",
  },
  hintText: {
    color: "#7A6F68",
    fontSize: 12,
    lineHeight: 18,
  },
  inlineLoading: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    marginBottom: 8,
  },
  emptyBox: {
    backgroundColor: "#FAF8F5",
    borderColor: "rgba(58,51,48,0.06)",
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 14,
  },
  emptyTitle: {
    color: "#2C2420",
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 4,
  },
  issueRow: {
    borderColor: "rgba(58,51,48,0.08)",
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  issueTitleRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 8,
  },
  issueTitle: {
    color: "#2C2420",
    fontSize: 14,
    fontWeight: "700",
  },
  typeBadge: {
    backgroundColor: "#F5EFE6",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  typeBadgeText: {
    color: "#8A6D3B",
    fontSize: 10,
    fontWeight: "700",
  },
  issueMeta: {
    color: "#7A6F68",
    fontSize: 11,
    marginTop: 3,
  },
  fieldHint: {
    color: "#9B8F86",
    fontSize: 11,
    lineHeight: 16,
    marginBottom: 8,
  },
  evidenceActions: {
    flexDirection: "row",
    gap: 8,
  },
  evidenceAction: {
    flex: 1,
    marginTop: 0,
  },
  modalBackdrop: {
    backgroundColor: "rgba(26,22,20,0.45)",
    flex: 1,
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: "#FAF8F5",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "92%",
    paddingBottom: 24,
    paddingHorizontal: 18,
    paddingTop: 16,
  },
  modalHandle: {
    alignSelf: "center",
    backgroundColor: "rgba(58,51,48,0.18)",
    borderRadius: 999,
    height: 4,
    marginBottom: 14,
    width: 42,
  },
  modalHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  modalTitle: {
    color: "#2C2420",
    flex: 1,
    fontFamily: "serif",
    fontSize: 22,
    marginRight: 12,
  },
  closeButton: {
    alignItems: "center",
    backgroundColor: "rgba(58,51,48,0.08)",
    borderRadius: 999,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  fieldLabel: {
    color: "#7A6F68",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.3,
    marginBottom: 7,
    marginTop: 12,
  },
  optionChip: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(58,51,48,0.12)",
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  optionChipActive: {
    backgroundColor: "rgba(201,168,106,0.12)",
    borderColor: "rgba(201,168,106,0.55)",
  },
  optionChipTitle: {
    color: "#2C2420",
    fontSize: 13,
    fontWeight: "700",
  },
  optionChipMeta: {
    color: "#7A6F68",
    fontSize: 11,
    marginTop: 2,
  },
  typeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  typeChip: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(58,51,48,0.12)",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  typeChipActive: {
    backgroundColor: "#3A3330",
    borderColor: "#3A3330",
  },
  typeChipText: {
    color: "#7A6F68",
    fontSize: 11,
    fontWeight: "600",
  },
  typeChipTextActive: {
    color: "#FFFFFF",
  },
  input: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(58,51,48,0.12)",
    borderRadius: 12,
    borderWidth: 1,
    color: "#2C2420",
    fontSize: 14,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  textArea: {
    minHeight: 96,
    textAlignVertical: "top",
  },
  fileRow: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(58,51,48,0.1)",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  fileName: {
    color: "#2C2420",
    flex: 1,
    fontSize: 12,
    marginRight: 10,
  },
  removeFileText: {
    color: "#B45309",
    fontSize: 11,
    fontWeight: "700",
  },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: "rgba(201,168,106,0.12)",
    borderRadius: 12,
    marginTop: 8,
    paddingVertical: 11,
  },
  secondaryButtonText: {
    color: "#8A6D3B",
    fontSize: 13,
    fontWeight: "700",
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "#3A3330",
    borderRadius: 14,
    marginTop: 16,
    paddingVertical: 13,
  },
  primaryButtonDisabled: {
    opacity: 0.65,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  errorText: {
    color: "#DC2626",
    fontSize: 12,
    marginTop: 10,
  },
  inputError: {
    borderColor: "rgba(220,38,38,0.45)",
  },
  detailBlock: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(58,51,48,0.08)",
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 10,
    padding: 14,
  },
  detailLabel: {
    color: "#7A6F68",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  detailValue: {
    color: "#2C2420",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  filterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 4,
    marginTop: 4,
  },
  filterChip: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(58,51,48,0.12)",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  filterChipActive: {
    backgroundColor: "#3A3330",
    borderColor: "#3A3330",
  },
  filterChipText: {
    color: "#7A6F68",
    fontSize: 11,
    fontWeight: "600",
  },
  filterChipTextActive: {
    color: "#FFFFFF",
  },
  statusOpen: {
    backgroundColor: "#FFF3E0",
  },
  statusOpenText: {
    color: "#E65100",
  },
  statusResolved: {
    backgroundColor: "#E8F5E9",
  },
  statusResolvedText: {
    color: "#2E7D32",
  },
  evidenceThumb: {
    borderRadius: 10,
    height: 72,
    marginTop: 8,
    width: 72,
  },
  evidenceFileChip: {
    alignItems: "center",
    backgroundColor: "#FAF8F5",
    borderColor: "rgba(58,51,48,0.08)",
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: "row",
    marginTop: 8,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  evidenceFileChipText: {
    color: "#8A6D3B",
    flex: 1,
    fontSize: 12,
    fontWeight: "600",
  },
  evidenceLink: {
    color: "#8A6D3B",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 8,
  },
});
