import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: "#FAF8F5",
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 32,
  },
  header: {
    backgroundColor: "#3A3330",
    paddingHorizontal: 19,
    paddingTop: Platform.OS === "ios" ? 54 : 38,
    paddingBottom: 20,
  },
  headerRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
  },
  backButton: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 999,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  brandText: {
    color: "rgba(255,255,255,0.55)",
    fontSize: 10,
    letterSpacing: 1.2,
  },
  headerTitle: {
    color: "#FFFFFF",
    fontFamily: "serif",
    fontSize: 28,
    marginTop: 2,
  },
  headerSubtitle: {
    color: "rgba(255,255,255,0.55)",
    fontSize: 11,
    marginTop: 4,
  },
  content: {
    paddingHorizontal: 19,
    paddingTop: 18,
  },
  centerState: {
    alignItems: "center",
    gap: 12,
    justifyContent: "center",
    minHeight: 280,
    paddingHorizontal: 24,
  },
  stateText: {
    color: "#7A6F68",
    fontSize: 13,
    lineHeight: 20,
    textAlign: "center",
  },
  retryButton: {
    backgroundColor: "#3A3330",
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  retryText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "600",
  },
  summaryCard: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(58,51,48,0.08)",
    borderRadius: 18,
    borderTopColor: "#2563EB",
    borderTopWidth: 3,
    borderWidth: 1,
    marginBottom: 14,
    padding: 18,
  },
  summaryLabel: {
    color: "#7A6F68",
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  summaryAmount: {
    color: "#3A3330",
    fontFamily: "serif",
    fontSize: 34,
    marginTop: 8,
  },
  summaryMeta: {
    color: "#7A6F68",
    fontSize: 12,
    marginTop: 6,
  },
  statusPill: {
    alignSelf: "flex-start",
    backgroundColor: "#F5F2ED",
    borderRadius: 999,
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  statusPillProcessing: {
    backgroundColor: "rgba(37,99,235,0.12)",
  },
  statusPillPaid: {
    backgroundColor: "rgba(22,163,74,0.12)",
  },
  statusPillText: {
    color: "#7A6F68",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  statusPillTextProcessing: {
    color: "#2563EB",
  },
  statusPillTextPaid: {
    color: "#15803D",
  },
  checkoutCard: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(58,51,48,0.08)",
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 14,
    padding: 18,
  },
  checkoutTitle: {
    color: "#3A3330",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 8,
  },
  checkoutText: {
    color: "#7A6F68",
    fontSize: 12,
    lineHeight: 18,
  },
  qrCard: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(58,51,48,0.08)",
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 14,
    padding: 20,
  },
  stepBadge: {
    alignSelf: "center",
    backgroundColor: "rgba(37,99,235,0.12)",
    borderRadius: 999,
    marginBottom: 10,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  stepBadgeText: {
    color: "#2563EB",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  qrTitle: {
    color: "#3A3330",
    fontSize: 15,
    fontWeight: "600",
    marginBottom: 16,
  },
  infoCard: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(58,51,48,0.08)",
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 14,
    padding: 16,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
  },
  infoLabel: {
    color: "#7A6F68",
    fontSize: 12,
  },
  infoValue: {
    color: "#3A3330",
    fontSize: 12,
    fontWeight: "600",
  },
  successCard: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(22,163,74,0.18)",
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 14,
    padding: 24,
  },
  successTitle: {
    color: "#15803D",
    fontFamily: "serif",
    fontSize: 20,
    marginTop: 10,
  },
  successText: {
    color: "#7A6F68",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 8,
    textAlign: "center",
  },
  footerActions: {
    gap: 10,
    marginTop: 4,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "#2563EB",
    borderRadius: 999,
    paddingVertical: 14,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "600",
  },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(58,51,48,0.12)",
    borderRadius: 999,
    borderWidth: 1,
    paddingVertical: 14,
  },
  secondaryButtonText: {
    color: "#3A3330",
    fontSize: 13,
    fontWeight: "600",
  },
  waitingRow: {
    alignItems: "center",
    backgroundColor: "rgba(37,99,235,0.08)",
    borderRadius: 12,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    marginTop: 12,
    paddingVertical: 12,
  },
  waitingText: {
    color: "#7A6F68",
    fontSize: 11,
    fontWeight: "500",
  },
});
