import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: "#FAF8F5",
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 32,
  },
  header: {
    backgroundColor: "#3A3330",
    paddingBottom: 20,
    paddingHorizontal: 19,
    paddingTop: 12,
  },
  headerRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 11,
  },
  backButton: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 15,
    height: 30,
    justifyContent: "center",
    width: 30,
  },
  brandText: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 10,
    letterSpacing: 1,
  },
  headerTitle: {
    color: "#FFFFFF",
    fontFamily: "serif",
    fontSize: 22,
    marginTop: 2,
  },
  headerSubtitle: {
    color: "rgba(255,255,255,0.55)",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 12,
  },
  content: {
    padding: 14,
  },
  sectionCard: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(60,51,48,0.08)",
    borderRadius: 14,
    borderWidth: 1,
    marginBottom: 14,
    padding: 14,
    shadowColor: "#3A3330",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
  },
  sectionTitle: {
    color: "#3A3330",
    fontSize: 15,
    fontWeight: "600",
    marginBottom: 14,
  },
  fieldRow: {
    flexDirection: "row",
    gap: 10,
  },
  fieldColumn: {
    flex: 1,
    minWidth: 0,
  },
  fieldGroup: {
    marginBottom: 14,
  },
  label: {
    color: "#7A6F68",
    fontSize: 11,
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  requiredMark: {
    color: "#C9A86A",
  },
  input: {
    backgroundColor: "#F8F5F1",
    borderColor: "rgba(60,51,48,0.08)",
    borderRadius: 12,
    borderWidth: 1,
    color: "#2C2420",
    fontSize: 14,
    minHeight: 46,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  inputSuffixWrap: {
    position: "relative",
  },
  inputWithSuffix: {
    paddingRight: 48,
  },
  inputSuffix: {
    color: "#7A6F68",
    fontSize: 10,
    fontWeight: "600",
    position: "absolute",
    right: 12,
    top: 17,
  },
  inputMultiline: {
    minHeight: 96,
    textAlignVertical: "top",
  },
  inputError: {
    borderColor: "#E24B4A",
  },
  selectField: {
    alignItems: "center",
    backgroundColor: "#F8F5F1",
    borderColor: "rgba(60,51,48,0.08)",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 46,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  selectFieldOpen: {
    borderColor: "#C9A86A",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  selectValue: {
    color: "#2C2420",
    flex: 1,
    fontSize: 14,
  },
  selectPlaceholder: {
    color: "#B8ADA4",
  },
  selectChevronOpen: {
    transform: [{ rotate: "180deg" }],
  },
  selectOptions: {
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    borderColor: "#C9A86A",
    borderTopWidth: 0,
    borderWidth: 1,
    overflow: "hidden",
  },
  uploadArea: {
    alignItems: "center",
    borderColor: "rgba(60,51,48,0.18)",
    borderRadius: 12,
    borderStyle: "dashed",
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 126,
    padding: 18,
  },
  uploadIcon: {
    alignItems: "center",
    backgroundColor: "#F1ECE5",
    borderRadius: 20,
    height: 40,
    justifyContent: "center",
    marginBottom: 9,
    width: 40,
  },
  uploadTitle: {
    color: "#3A3330",
    fontSize: 13,
    fontWeight: "600",
  },
  uploadHint: {
    color: "#9B8F86",
    fontSize: 10,
    marginTop: 4,
  },
  fileRow: {
    alignItems: "center",
    backgroundColor: "#F8F5F1",
    borderRadius: 10,
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
    padding: 10,
  },
  fileInfo: {
    flex: 1,
  },
  fileName: {
    color: "#3A3330",
    fontSize: 12,
    fontWeight: "500",
  },
  fileSize: {
    color: "#9B8F86",
    fontSize: 10,
    marginTop: 2,
  },
  selectOption: {
    justifyContent: "center",
    minHeight: 42,
    paddingHorizontal: 14,
  },
  selectOptionDivider: {
    borderBottomColor: "rgba(60,51,48,0.08)",
    borderBottomWidth: 1,
  },
  selectOptionSelected: {
    backgroundColor: "#F1ECE5",
  },
  selectOptionText: {
    color: "#2C2420",
    fontSize: 14,
  },
  selectOptionTextSelected: {
    color: "#A77D35",
    fontWeight: "600",
  },
  errorText: {
    color: "#E24B4A",
    fontSize: 11,
    marginTop: 4,
  },
  submitButton: {
    alignItems: "center",
    backgroundColor: "#3A3330",
    borderRadius: 14,
    marginTop: 8,
    paddingVertical: 14,
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  hintText: {
    color: "#7A6F68",
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 16,
  },
  dateField: {
    alignItems: "center",
    backgroundColor: "#F8F5F1",
    borderColor: "rgba(60,51,48,0.08)",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    minHeight: 46,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  dateFieldMain: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: 10,
  },
  dateFieldText: {
    color: "#2C2420",
    flex: 1,
    fontSize: 14,
  },
  dateFieldPlaceholder: {
    color: "#B8ADA4",
  },
  dateClearText: {
    color: "#C9A86A",
    fontSize: 12,
    fontWeight: "600",
  },
  datePickerDoneButton: {
    alignItems: "flex-end",
    marginBottom: 8,
    marginTop: 4,
  },
  datePickerDoneText: {
    color: "#C9A86A",
    fontSize: 14,
    fontWeight: "600",
  },
});
