import { StyleSheet } from "react-native";

export const orderDetailStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#F5F0EA" },
  scrollContent: { paddingBottom: 40 },
  hero: {
    backgroundColor: "#2A2420",
    overflow: "hidden",
    paddingBottom: 30,
    paddingHorizontal: 20,
    paddingTop: 54,
  },
  heroDecor: {
    backgroundColor: "rgba(201,168,106,0.13)",
    borderRadius: 80,
    height: 160,
    position: "absolute",
    right: -45,
    top: -55,
    width: 160,
  },
  heroRow: { alignItems: "center", flexDirection: "row", gap: 14 },
  backButton: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.09)",
    borderRadius: 19,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  heroText: { flex: 1, minWidth: 0 },
  brand: { color: "#C9A86A", fontSize: 10, fontWeight: "700", letterSpacing: 1.8 },
  title: { color: "#FFFFFF", fontSize: 24, fontWeight: "800", marginTop: 3 },
  projectName: { color: "#C9C0B8", fontSize: 13, marginTop: 12 },
  content: { gap: 14, paddingHorizontal: 16, paddingTop: 16 },
  card: {
    backgroundColor: "#FFFFFF",
    borderColor: "#EDE5DC",
    borderRadius: 18,
    borderWidth: 1,
    padding: 16,
  },
  cardHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  cardLabel: { color: "#9B8F86", fontSize: 10, fontWeight: "700", letterSpacing: 1.1 },
  statusPill: { backgroundColor: "#F5EFE6", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5 },
  statusText: { color: "#8A6D3B", fontSize: 10, fontWeight: "700" },
  statusComplete: { backgroundColor: "#ECFDF5" },
  statusCompleteText: { color: "#059669" },
  totalBlock: {
    backgroundColor: "#2A2420",
    borderRadius: 15,
    marginBottom: 14,
    padding: 16,
  },
  totalLabel: { color: "#B8ADA4", fontSize: 10, fontWeight: "700", letterSpacing: 1 },
  totalValue: { color: "#E8D4A8", fontSize: 25, fontWeight: "800", marginTop: 5 },
  moneyRow: {
    alignItems: "center",
    borderBottomColor: "#F0EAE3",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 10,
  },
  moneyRowLast: { borderBottomWidth: 0 },
  moneyLabel: { color: "#7A6F68", fontSize: 13 },
  moneyValue: { color: "#2A2420", fontSize: 13, fontWeight: "700" },
  itemRow: {
    borderBottomColor: "#F0EAE3",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 12,
    paddingVertical: 12,
  },
  itemRowLast: { borderBottomWidth: 0 },
  itemIndex: {
    alignItems: "center",
    backgroundColor: "#F5EFE6",
    borderRadius: 10,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  itemIndexText: { color: "#8A6D3B", fontSize: 11, fontWeight: "800" },
  itemMain: { flex: 1, minWidth: 0 },
  itemName: { color: "#2A2420", fontSize: 14, fontWeight: "700", lineHeight: 19 },
  itemMeta: { color: "#9B8F86", fontSize: 11, marginTop: 4 },
  itemAmount: { color: "#2A2420", fontSize: 12, fontWeight: "700" },
  actionCard: { backgroundColor: "#FFFFFF", borderColor: "#EDE5DC", borderRadius: 18, borderWidth: 1, padding: 16 },
  actionTitle: { color: "#2A2420", fontSize: 16, fontWeight: "800" },
  actionSubtitle: { color: "#7A6F68", fontSize: 12, lineHeight: 18, marginTop: 4 },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "#3A3330",
    borderRadius: 13,
    marginTop: 14,
    paddingVertical: 15,
  },
  primaryButtonText: { color: "#FFFFFF", fontSize: 14, fontWeight: "700" },
  buttonDisabled: { opacity: 0.55 },
  actionLoading: { alignItems: "center", flexDirection: "row", gap: 9, marginTop: 14 },
  actionLoadingText: { color: "#9B8F86", fontSize: 12 },
  noteCard: {
    alignItems: "center",
    backgroundColor: "#FFFBF5",
    borderColor: "#EAD8B7",
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    padding: 14,
  },
  noteDot: { backgroundColor: "#C9A86A", borderRadius: 4, height: 8, width: 8 },
  noteText: { color: "#5C524C", flex: 1, fontSize: 13, lineHeight: 19 },
  state: { alignItems: "center", gap: 12, paddingHorizontal: 24, paddingVertical: 72 },
  stateText: { color: "#7A6F68", fontSize: 13, lineHeight: 20, textAlign: "center" },
  retryButton: { backgroundColor: "#3A3330", borderRadius: 12, paddingHorizontal: 20, paddingVertical: 11 },
  retryText: { color: "#FFFFFF", fontSize: 13, fontWeight: "700" },
});
