import { StyleSheet } from "react-native";

export const projectOrdersStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#F5F0EA",
  },
  scrollContent: {
    paddingBottom: 40,
  },
  hero: {
    backgroundColor: "#2A2420",
    paddingHorizontal: 20,
    paddingTop: 56,
    paddingBottom: 32,
    overflow: "hidden",
  },
  heroDecor: {
    position: "absolute",
    top: -40,
    right: -30,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: "rgba(201, 168, 106, 0.12)",
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  heroEyebrow: {
    fontSize: 10,
    letterSpacing: 2,
    color: "#C9A86A",
    fontWeight: "600",
    marginBottom: 6,
  },
  heroTitle: {
    fontSize: 26,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  heroProject: {
    fontSize: 14,
    color: "#D4CCC4",
    marginTop: 10,
    lineHeight: 20,
  },
  content: {
    paddingHorizontal: 16,
    marginTop: -16,
    gap: 12,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 4,
    marginBottom: 2,
  },
  sectionTitle: {
    fontSize: 11,
    letterSpacing: 1.2,
    fontWeight: "700",
    color: "#9B8F86",
  },
  sectionCount: {
    fontSize: 11,
    fontWeight: "600",
    color: "#B8ADA4",
  },
  orderCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#EDE5DC",
    shadowColor: "#2A2420",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  cardTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  orderBadge: {
    backgroundColor: "#F5EFE6",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  orderBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#8A6D3B",
  },
  statusPill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "#F5EFE6",
  },
  statusPillText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#8A6D3B",
    letterSpacing: 0.4,
  },
  statusDeposit: {
    backgroundColor: "#EFF6FF",
  },
  statusDepositText: {
    color: "#2563EB",
  },
  statusProduction: {
    backgroundColor: "#FFFBEB",
  },
  statusProductionText: {
    color: "#D97706",
  },
  statusDelivery: {
    backgroundColor: "#F0F9FF",
  },
  statusDeliveryText: {
    color: "#0284C7",
  },
  statusPayment: {
    backgroundColor: "#FFF7ED",
  },
  statusPaymentText: {
    color: "#EA580C",
  },
  statusCompleted: {
    backgroundColor: "#ECFDF5",
  },
  statusCompletedText: {
    color: "#059669",
  },
  statusCancelled: {
    backgroundColor: "#FEF2F2",
  },
  statusCancelledText: {
    color: "#DC2626",
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#2A2420",
    marginBottom: 4,
  },
  cardCode: {
    fontSize: 11,
    color: "#9B8F86",
    letterSpacing: 0.2,
    marginBottom: 14,
  },
  amountRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  amountLabel: {
    fontSize: 11,
    letterSpacing: 1,
    fontWeight: "700",
    color: "#9B8F86",
    marginBottom: 4,
  },
  amountValue: {
    fontSize: 24,
    fontWeight: "800",
    color: "#C9A86A",
    letterSpacing: -0.5,
  },
  depositDueBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#EFF6FF",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    marginBottom: 12,
  },
  depositDueText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#2563EB",
    letterSpacing: 0.3,
  },
  cardFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#F0EAE3",
  },
  metaText: {
    flex: 1,
    fontSize: 12,
    color: "#7A6F68",
    lineHeight: 18,
    paddingRight: 8,
  },
  chevronWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#F5F0EA",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 24,
    borderWidth: 1,
    borderColor: "#EDE5DC",
    alignItems: "center",
  },
  emptyIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#F5EFE6",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  emptyIconText: {
    fontSize: 20,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#2A2420",
    marginBottom: 8,
    textAlign: "center",
  },
  emptyText: {
    fontSize: 13,
    color: "#7A6F68",
    lineHeight: 20,
    textAlign: "center",
  },
  loadingWrap: {
    paddingVertical: 48,
    alignItems: "center",
    gap: 12,
  },
  loadingText: {
    fontSize: 13,
    color: "#7A6F68",
  },
});
