import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: "#FAF8F5",
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  header: {
    backgroundColor: "#3A3330",
    paddingHorizontal: 19,
    paddingTop: 38,
    paddingBottom: 22,
  },
  headerTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 11,
  },
  backButton: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 15,
    height: 30,
    justifyContent: "center",
    width: 30,
  },
  brandText: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 10,
    letterSpacing: 1,
  },
  headerTitle: {
    color: "#FFFFFF",
    fontFamily: "serif",
    fontSize: 25,
    marginTop: 2,
  },
  summaryCard: {
    backgroundColor: "rgba(255,255,255,0.08)",
    borderColor: "rgba(255,255,255,0.1)",
    borderRadius: 15,
    borderWidth: 1,
    marginTop: 19,
    padding: 16,
  },
  summaryTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  projectName: {
    color: "#FFFFFF",
    fontFamily: "serif",
    fontSize: 24,
  },
  projectMeta: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 11,
    marginTop: 2,
  },
  activePill: {
    alignItems: "center",
    backgroundColor: "rgba(255,185,0,0.2)",
    borderColor: "rgba(255,185,0,0.3)",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 5,
    height: 24,
    marginTop: 1,
    paddingHorizontal: 10,
  },
  activePillDot: {
    backgroundColor: "#FFB900",
    borderRadius: 3,
    height: 6,
    width: 6,
  },
  activePillText: {
    color: "#FFD230",
    fontSize: 10,
    letterSpacing: 0.25,
  },
  stageRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
  },
  stageText: {
    color: "rgba(255,255,255,0.55)",
    fontSize: 11,
  },
  stagePercent: {
    color: "#C9A86A",
    fontSize: 11,
  },
  progressTrack: {
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 999,
    height: 4,
    marginTop: 5,
    overflow: "hidden",
  },
  progressFill: {
    backgroundColor: "#C9A86A",
    height: 4,
    width: "25%",
  },
  content: {
    padding: 19,
  },
  metricsRow: {
    flexDirection: "row",
    gap: 9,
  },
  metricCard: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(60,51,48,0.05)",
    borderRadius: 15,
    borderWidth: 1,
    flex: 1,
    paddingVertical: 12,
  },
  metricValue: {
    color: "#C9A86A",
    fontFamily: "serif",
    fontSize: 18,
  },
  metricLabel: {
    color: "#7A6F68",
    fontSize: 10,
    letterSpacing: 0.25,
    marginTop: 1,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(60,51,48,0.05)",
    borderRadius: 15,
    borderWidth: 1,
    marginTop: 15,
    padding: 16,
  },
  cardLabel: {
    color: "#7A6F68",
    fontSize: 10,
    letterSpacing: 1,
  },
  teamRow: {
    alignItems: "center",
    flexDirection: "row",
    marginTop: 11,
  },
  teamAvatar: {
    alignItems: "center",
    borderRadius: 19,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  teamInitials: {
    color: "#FFFFFF",
    fontSize: 11,
  },
  teamTextWrap: {
    flex: 1,
    marginLeft: 11,
  },
  teamName: {
    color: "#2C2420",
    fontSize: 13,
  },
  teamRole: {
    color: "#7A6F68",
    fontSize: 11,
  },
  teamActions: {
    flexDirection: "row",
    gap: 8,
  },
  teamActionButton: {
    alignItems: "center",
    backgroundColor: "#F5F2ED",
    borderRadius: 14,
    height: 26,
    justifyContent: "center",
    width: 26,
  },
  timelineList: {
    marginTop: 10,
  },
  timelineRow: {
    flexDirection: "row",
    minHeight: 62,
  },
  timelineRowLast: {
    minHeight: 47,
  },
  timelineRailWrap: {
    alignItems: "center",
    marginRight: 13,
    width: 26,
  },
  timelineDot: {
    alignItems: "center",
    backgroundColor: "#E8E4DF",
    borderColor: "rgba(60,51,48,0.12)",
    borderRadius: 13,
    borderWidth: 1,
    height: 26,
    justifyContent: "center",
    width: 26,
  },
  timelineDotDone: {
    backgroundColor: "#ECFDF5",
    borderColor: "#A4F4CF",
  },
  timelineDotActive: {
    backgroundColor: "rgba(201,168,106,0.15)",
    borderColor: "rgba(201,168,106,0.4)",
  },
  timelineDotPending: {
    backgroundColor: "#E8E4DF",
  },
  timelineLine: {
    backgroundColor: "#E8E4DF",
    flex: 1,
    marginTop: 4,
    width: 1,
  },
  timelineLineDone: {
    backgroundColor: "#86EFAC",
  },
  timelineLineActive: {
    backgroundColor: "rgba(201,168,106,0.35)",
  },
  timelineContent: {
    flex: 1,
    paddingBottom: 15,
  },
  timelineHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  timelineTitle: {
    color: "#2C2420",
    fontSize: 13,
  },
  timelineTitleActive: {
    color: "#C9A86A",
    fontFamily: "serif",
  },
  timelineTitlePending: {
    color: "#7A6F68",
  },
  timelineSubtitle: {
    color: "rgba(122,111,104,0.7)",
    fontSize: 11,
    marginTop: 1,
  },
  timelineDateWrap: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
    paddingLeft: 7,
  },
  timelineDateText: {
    color: "#7A6F68",
    fontSize: 10,
  },
  timelineNote: {
    backgroundColor: "rgba(201,168,106,0.06)",
    borderColor: "rgba(201,168,106,0.2)",
    borderRadius: 11,
    borderWidth: 1,
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  timelineNoteText: {
    color: "#7A6F68",
    fontSize: 11,
    lineHeight: 18,
  },
  completionCard: {
    backgroundColor: "#3A3330",
    borderRadius: 15,
    flexDirection: "row",
    gap: 15,
    marginTop: 15,
    paddingHorizontal: 19,
    paddingVertical: 15,
  },
  completionIconWrap: {
    alignItems: "center",
    justifyContent: "center",
    width: 30,
  },
  completionLabel: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 10,
    letterSpacing: 1,
  },
  completionDate: {
    color: "#FFFFFF",
    fontFamily: "serif",
    fontSize: 16,
    marginTop: 2,
  },
  completionMeta: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 11,
    marginTop: 2,
  },
  bottomNav: {
    backgroundColor: "rgba(255,255,255,0.95)",
    borderTopColor: "rgba(60,51,48,0.08)",
    borderTopWidth: 1,
    bottom: 0,
    flexDirection: "row",
    height: 74,
    left: 0,
    position: "absolute",
    right: 0,
  },
  bottomItem: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
  },
  bottomIconWrap: {
    position: "relative",
  },
  bottomBadge: {
    alignItems: "center",
    backgroundColor: "#C9A86A",
    borderRadius: 8,
    height: 15,
    justifyContent: "center",
    position: "absolute",
    right: -10,
    top: -5,
    width: 15,
  },
  bottomBadgeText: {
    color: "#FFFFFF",
    fontSize: 9,
  },
  bottomLabel: {
    color: "rgba(122,111,104,0.7)",
    fontSize: 10,
    marginTop: 4,
  },
  bottomLabelActive: {
    color: "#C9A86A",
  },
  bottomActiveIndicator: {
    backgroundColor: "#C9A86A",
    borderRadius: 999,
    height: 2,
    position: "absolute",
    top: 6,
    width: 20,
  },
});
