import { StyleSheet } from "react-native";

export const projectSchedulesStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#F5F0EA",
  },
  scrollContent: {
    paddingBottom: 40,
  },
  hero: {
    backgroundColor: "#2A2420",
    paddingHorizontal: 20,
    paddingTop: 56,
    paddingBottom: 40,
    overflow: "hidden",
  },
  heroDecorPrimary: {
    position: "absolute",
    top: -50,
    right: -40,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: "rgba(201, 168, 106, 0.14)",
  },
  heroDecorSecondary: {
    position: "absolute",
    bottom: -20,
    left: -30,
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  heroTopRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 22,
  },
  backButton: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderColor: "rgba(255,255,255,0.06)",
    borderRadius: 18,
    borderWidth: 1,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  heroIconWrap: {
    alignItems: "center",
    backgroundColor: "rgba(201,168,106,0.15)",
    borderColor: "rgba(201,168,106,0.25)",
    borderRadius: 14,
    borderWidth: 1,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  heroEyebrow: {
    color: "#C9A86A",
    fontSize: 10,
    fontWeight: "600",
    letterSpacing: 2,
    marginBottom: 6,
  },
  heroTitle: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "800",
    letterSpacing: -0.4,
  },
  heroProject: {
    color: "#D4CCC4",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  statsStrip: {
    backgroundColor: "#FFFFFF",
    borderColor: "#EDE5DC",
    borderRadius: 16,
    borderWidth: 1,
    elevation: 3,
    flexDirection: "row",
    marginHorizontal: 16,
    marginTop: -22,
    paddingVertical: 14,
    shadowColor: "#2A2420",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
  },
  statItem: {
    alignItems: "center",
    flex: 1,
    gap: 4,
  },
  statValue: {
    color: "#2A2420",
    fontSize: 20,
    fontWeight: "800",
    letterSpacing: -0.3,
  },
  statValueAccent: {
    color: "#C9A86A",
  },
  statLabel: {
    color: "#9B8F86",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.8,
  },
  statDivider: {
    alignSelf: "center",
    backgroundColor: "#EDE5DC",
    height: 32,
    width: 1,
  },
  content: {
    gap: 14,
    marginTop: 16,
    paddingHorizontal: 16,
  },
  sectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    marginBottom: 2,
    paddingHorizontal: 4,
  },
  sectionDot: {
    backgroundColor: "#C9A86A",
    borderRadius: 3,
    height: 6,
    width: 6,
  },
  sectionDotMuted: {
    backgroundColor: "#C4B8AE",
  },
  sectionTitle: {
    color: "#9B8F86",
    flex: 1,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.2,
  },
  sectionCount: {
    backgroundColor: "#F5EFE6",
    borderRadius: 999,
    color: "#8A6D3B",
    fontSize: 10,
    fontWeight: "700",
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  scheduleCardWrap: {
    borderRadius: 20,
    overflow: "hidden",
  },
  scheduleCardWrapPending: {
    shadowColor: "#C9A86A",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 5,
  },
  scheduleCardInner: {
    backgroundColor: "#FFFFFF",
    borderColor: "#EDE5DC",
    borderRadius: 20,
    borderWidth: 1,
    overflow: "hidden",
  },
  scheduleCardInnerPending: {
    borderColor: "rgba(201,168,106,0.45)",
  },
  cardBanner: {
    backgroundColor: "#FBF7F2",
    borderBottomColor: "#F0EAE3",
    borderBottomWidth: 1,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 16,
  },
  cardBannerPending: {
    backgroundColor: "#FFFBF5",
  },
  cardBannerTop: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  cardBannerLeft: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  typeIconWrap: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(201,168,106,0.25)",
    borderRadius: 12,
    borderWidth: 1,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  typeBadge: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E8DFD4",
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  typeBadgeText: {
    color: "#8A6D3B",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.6,
  },
  statusPill: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#FDE68A",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  statusDot: {
    backgroundColor: "#D97706",
    borderRadius: 3,
    height: 6,
    width: 6,
  },
  statusPillText: {
    color: "#B45309",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  statusPillConfirmed: {
    backgroundColor: "#ECFDF5",
    borderColor: "#A7F3D0",
  },
  statusDotConfirmed: {
    backgroundColor: "#059669",
  },
  statusPillConfirmedText: {
    color: "#047857",
  },
  cardTitle: {
    color: "#2A2420",
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: -0.2,
    lineHeight: 24,
  },
  cardSubtitle: {
    color: "#9B8F86",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
  scheduleCardBody: {
    gap: 14,
    padding: 16,
  },
  timeSection: {
    gap: 10,
  },
  timeSectionLabel: {
    color: "#9B8F86",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  timeGrid: {
    backgroundColor: "#F8F4EF",
    borderColor: "#EDE5DC",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    overflow: "hidden",
  },
  timeSlot: {
    flex: 1,
    gap: 4,
    minWidth: 0,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  timeSlotLabel: {
    color: "#9B8F86",
    fontSize: 11,
    fontWeight: "600",
  },
  timeSlotDate: {
    color: "#2A2420",
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 20,
  },
  timeSlotTime: {
    color: "#8A6D3B",
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
  },
  timeGridDivider: {
    alignSelf: "stretch",
    backgroundColor: "#EDE5DC",
    width: 1,
  },
  infoPanel: {
    backgroundColor: "#FAFAF8",
    borderColor: "#EDE5DC",
    borderRadius: 16,
    borderWidth: 1,
    overflow: "hidden",
  },
  infoRow: {
    alignItems: "center",
    borderBottomColor: "#F0EAE3",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  infoRowLast: {
    borderBottomWidth: 0,
  },
  infoRowIconWrap: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#F0EAE3",
    borderRadius: 10,
    borderWidth: 1,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  infoRowContent: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  infoRowLabel: {
    color: "#9B8F86",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  infoRowValue: {
    color: "#2A2420",
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 20,
  },
  detailsSection: {
    gap: 8,
  },
  detailsTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  detailsTitle: {
    color: "#2A2420",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  detailsLine: {
    backgroundColor: "#EDE5DC",
    flex: 1,
    height: 1,
  },
  noteBox: {
    backgroundColor: "#FAFAF8",
    borderColor: "#F0EAE3",
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  description: {
    color: "#5C534D",
    fontSize: 13,
    lineHeight: 20,
  },
  descriptionMuted: {
    color: "#9B8F86",
    fontSize: 13,
    fontStyle: "italic",
    lineHeight: 20,
  },
  cardFooter: {
    backgroundColor: "#FBF9F7",
    borderTopColor: "#F0EAE3",
    borderTopWidth: 1,
    gap: 12,
    marginHorizontal: -16,
    marginBottom: -16,
    marginTop: 2,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  confirmHint: {
    color: "#9B8F86",
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
  },
  confirmButton: {
    alignItems: "center",
    backgroundColor: "#3A3330",
    borderRadius: 14,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    paddingVertical: 15,
    shadowColor: "#2A2420",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 3,
  },
  confirmButtonDisabled: {
    opacity: 0.6,
  },
  confirmButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  emptyCard: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#EDE5DC",
    borderRadius: 18,
    borderWidth: 1,
    padding: 28,
  },
  emptyIcon: {
    alignItems: "center",
    backgroundColor: "#F5EFE6",
    borderColor: "rgba(201,168,106,0.2)",
    borderRadius: 28,
    borderWidth: 1,
    height: 56,
    justifyContent: "center",
    marginBottom: 16,
    width: 56,
  },
  emptyTitle: {
    color: "#2A2420",
    fontSize: 17,
    fontWeight: "700",
    marginBottom: 8,
    textAlign: "center",
  },
  emptyText: {
    color: "#7A6F68",
    fontSize: 13,
    lineHeight: 20,
    textAlign: "center",
  },
  loadingWrap: {
    alignItems: "center",
    gap: 12,
    paddingVertical: 48,
  },
  loadingText: {
    color: "#7A6F68",
    fontSize: 13,
  },
});
