import { StyleSheet } from "react-native";

export const quotationDetailStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#F5F0EA",
  },
  scrollContent: {
    paddingBottom: 40,
  },
  hero: {
    backgroundColor: "#2A2420",
    paddingHorizontal: 20,
    paddingTop: 56,
    paddingBottom: 36,
    overflow: "hidden",
  },
  heroDecor: {
    position: "absolute",
    top: -40,
    right: -30,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: "rgba(201, 168, 106, 0.12)",
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  heroEyebrow: {
    fontSize: 10,
    letterSpacing: 2,
    color: "#C9A86A",
    fontWeight: "600",
    marginBottom: 6,
  },
  heroTitle: {
    fontSize: 26,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  heroCode: {
    fontSize: 12,
    color: "#B8ADA4",
    marginTop: 6,
    letterSpacing: 0.3,
  },
  heroProject: {
    fontSize: 14,
    color: "#D4CCC4",
    marginTop: 10,
    lineHeight: 20,
  },
  heroMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
    marginTop: 14,
  },
  statusPill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  statusPillText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#FFFFFF",
    letterSpacing: 0.4,
  },
  statusSent: {
    backgroundColor: "rgba(59, 130, 246, 0.2)",
  },
  statusSentText: {
    color: "#93C5FD",
  },
  statusAccepted: {
    backgroundColor: "rgba(34, 197, 94, 0.2)",
  },
  statusAcceptedText: {
    color: "#86EFAC",
  },
  statusRejected: {
    backgroundColor: "rgba(239, 68, 68, 0.2)",
  },
  statusRejectedText: {
    color: "#FCA5A5",
  },
  statusWarning: {
    backgroundColor: "rgba(245, 158, 11, 0.2)",
  },
  statusWarningText: {
    color: "#FCD34D",
  },
  statusMuted: {
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  statusMutedText: {
    color: "#B8ADA4",
  },
  heroMetaText: {
    fontSize: 12,
    color: "#9B8F86",
  },
  content: {
    paddingHorizontal: 16,
    marginTop: -20,
    gap: 14,
  },
  totalCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: "#EDE5DC",
    shadowColor: "#2A2420",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
  },
  totalCardLabel: {
    fontSize: 11,
    letterSpacing: 1.4,
    fontWeight: "700",
    color: "#9B8F86",
    marginBottom: 8,
  },
  totalCardAmount: {
    fontSize: 32,
    fontWeight: "800",
    color: "#C9A86A",
    letterSpacing: -0.5,
  },
  totalCardDeposit: {
    fontSize: 13,
    color: "#7A6F68",
    marginTop: 8,
  },
  sectionCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#EDE5DC",
  },
  sectionTitle: {
    fontSize: 11,
    letterSpacing: 1.2,
    fontWeight: "700",
    color: "#9B8F86",
    marginBottom: 14,
  },
  lineItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F0EAE3",
  },
  lineItemLast: {
    borderBottomWidth: 0,
    paddingBottom: 4,
  },
  lineItemHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  lineItemName: {
    flex: 1,
    fontSize: 15,
    fontWeight: "600",
    color: "#2A2420",
    lineHeight: 21,
  },
  lineItemAmount: {
    fontSize: 14,
    fontWeight: "700",
    color: "#2A2420",
  },
  lineItemMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 6,
  },
  qtyBadge: {
    backgroundColor: "#F5EFE6",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  qtyBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#8A6D3B",
  },
  lineItemUnitPrice: {
    fontSize: 12,
    color: "#9B8F86",
  },
  breakdownBox: {
    backgroundColor: "#FAF7F3",
    borderRadius: 12,
    padding: 14,
    marginTop: 4,
    gap: 10,
  },
  breakdownRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  breakdownLabel: {
    fontSize: 13,
    color: "#6B615A",
  },
  breakdownValue: {
    fontSize: 13,
    fontWeight: "600",
    color: "#2A2420",
  },
  breakdownDiscount: {
    color: "#C9A86A",
  },
  breakdownDivider: {
    height: 1,
    backgroundColor: "#EDE5DC",
    marginVertical: 2,
  },
  breakdownTotalLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: "#2A2420",
  },
  breakdownTotalValue: {
    fontSize: 18,
    fontWeight: "800",
    color: "#C9A86A",
  },
  noteBanner: {
    backgroundColor: "#FFFBEB",
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: "#FDE68A",
  },
  noteBannerLabel: {
    fontSize: 10,
    letterSpacing: 1,
    fontWeight: "700",
    color: "#B45309",
    marginBottom: 6,
  },
  noteBannerText: {
    fontSize: 13,
    color: "#78350F",
    lineHeight: 20,
  },
  expiredBanner: {
    backgroundColor: "#FEF2F2",
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: "#FECACA",
  },
  expiredBannerText: {
    fontSize: 13,
    color: "#B91C1C",
    lineHeight: 20,
    fontWeight: "600",
  },
  actionsCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#EDE5DC",
    gap: 10,
  },
  actionsTitle: {
    fontSize: 11,
    letterSpacing: 1.2,
    fontWeight: "700",
    color: "#9B8F86",
    marginBottom: 4,
  },
  primaryButton: {
    backgroundColor: "#C9A86A",
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: "center",
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
  },
  secondaryButton: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#D9CFC4",
  },
  secondaryButtonText: {
    color: "#5C524C",
    fontSize: 15,
    fontWeight: "600",
  },
  dangerButton: {
    backgroundColor: "#DC2626",
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: "center",
  },
  dangerButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  acceptedCard: {
    backgroundColor: "#ECFDF5",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#A7F3D0",
  },
  acceptedText: {
    fontSize: 13,
    color: "#047857",
    lineHeight: 20,
  },
  formCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#EDE5DC",
  },
  formLabel: {
    fontSize: 11,
    letterSpacing: 1.2,
    fontWeight: "700",
    color: "#9B8F86",
    marginBottom: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: "#D9CFC4",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: "#2A2420",
    backgroundColor: "#FAFAF8",
    minHeight: 96,
    textAlignVertical: "top",
  },
  loadingWrap: {
    paddingVertical: 48,
    alignItems: "center",
    gap: 12,
  },
  loadingText: {
    fontSize: 13,
    color: "#7A6F68",
  },
  emptyCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: "#EDE5DC",
  },
  emptyText: {
    fontSize: 13,
    color: "#7A6F68",
    lineHeight: 20,
    textAlign: "center",
  },
});
