import { StyleSheet } from "react-native";
import { DESIGNER } from "./designer.styles";

export const detailStyles = StyleSheet.create({
  hero: {
    backgroundColor: DESIGNER.charcoal,
    overflow: "hidden",
    paddingBottom: 16,
    paddingHorizontal: 19,
  },
  heroDecorLarge: {
    backgroundColor: "rgba(47,93,80,0.4)",
    borderRadius: 999,
    height: 160,
    position: "absolute",
    right: -52,
    top: -70,
    width: 160,
  },
  heroDecorMedium: {
    backgroundColor: "rgba(201,168,106,0.14)",
    borderRadius: 999,
    height: 96,
    left: -40,
    position: "absolute",
    top: 56,
    width: 96,
  },
  topRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
  },
  backButton: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 16,
    height: 32,
    justifyContent: "center",
    marginTop: 2,
    width: 32,
  },
  titleWrap: {
    flex: 1,
    minWidth: 0,
  },
  code: {
    color: "rgba(255,255,255,0.48)",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  title: {
    color: DESIGNER.white,
    fontFamily: "serif",
    fontSize: 22,
    fontWeight: "600",
    lineHeight: 28,
    marginTop: 4,
  },
  statusPill: {
    borderRadius: 999,
    borderWidth: 1,
    marginTop: 2,
    maxWidth: 118,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  statusPillText: {
    fontSize: 10,
    fontWeight: "700",
    textAlign: "center",
  },
  progressWrap: {
    marginTop: 16,
  },
  progressTrack: {
    alignItems: "center",
    flexDirection: "row",
  },
  progressDot: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderColor: "rgba(255,255,255,0.22)",
    borderRadius: 7,
    borderWidth: 1.5,
    height: 12,
    width: 12,
  },
  progressDotDone: {
    backgroundColor: DESIGNER.accent,
    borderColor: DESIGNER.accent,
  },
  progressDotCurrent: {
    backgroundColor: "rgba(201,168,106,0.25)",
    borderColor: DESIGNER.gold,
  },
  progressLine: {
    backgroundColor: "rgba(255,255,255,0.12)",
    flex: 1,
    height: 2,
    marginHorizontal: 2,
  },
  progressLineDone: {
    backgroundColor: DESIGNER.accent,
  },
  stageLabel: {
    color: "rgba(255,255,255,0.55)",
    fontSize: 10,
    fontWeight: "600",
    marginTop: 8,
  },
  tabsBar: {
    backgroundColor: DESIGNER.bg,
    borderBottomColor: DESIGNER.border,
    borderBottomWidth: 1,
  },
  tabs: {
    gap: 8,
    paddingHorizontal: 19,
    paddingVertical: 12,
  },
  tabChip: {
    backgroundColor: DESIGNER.white,
    borderColor: DESIGNER.border,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  tabChipActive: {
    backgroundColor: DESIGNER.accent,
    borderColor: DESIGNER.accent,
  },
  tabChipText: {
    color: DESIGNER.muted,
    fontSize: 11,
    fontWeight: "600",
  },
  tabChipTextActive: {
    color: DESIGNER.white,
  },
  body: {
    gap: 12,
    paddingBottom: 32,
    paddingHorizontal: 19,
    paddingTop: 16,
  },
  card: {
    backgroundColor: DESIGNER.white,
    borderColor: DESIGNER.border,
    borderRadius: 16,
    borderWidth: 1,
    overflow: "hidden",
    padding: 15,
  },
  cardAccent: {
    height: 3,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  sectionLabel: {
    color: DESIGNER.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  cardTitle: {
    color: DESIGNER.ink,
    fontFamily: "serif",
    fontSize: 18,
    fontWeight: "600",
    lineHeight: 24,
    marginTop: 8,
  },
  cardMeta: {
    color: DESIGNER.muted,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
  briefText: {
    color: DESIGNER.ink,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 10,
  },
  statusGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  statusCell: {
    backgroundColor: DESIGNER.pale,
    borderRadius: 14,
    minHeight: 74,
    paddingHorizontal: 12,
    paddingVertical: 11,
    width: "48.5%",
  },
  statusCellLabel: {
    color: DESIGNER.muted,
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  statusCellValue: {
    color: DESIGNER.ink,
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 18,
    marginTop: 6,
  },
  memberRow: {
    alignItems: "center",
    borderTopColor: DESIGNER.border,
    borderTopWidth: 1,
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
    paddingTop: 12,
  },
  memberRowFirst: {
    borderTopWidth: 0,
    marginTop: 10,
    paddingTop: 0,
  },
  memberAvatar: {
    alignItems: "center",
    backgroundColor: DESIGNER.accent,
    borderRadius: 16,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  memberAvatarSales: {
    backgroundColor: DESIGNER.charcoal,
  },
  memberAvatarText: {
    color: DESIGNER.white,
    fontFamily: "serif",
    fontSize: 11,
    fontWeight: "600",
  },
  memberRole: {
    color: DESIGNER.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  memberName: {
    color: DESIGNER.ink,
    fontSize: 13,
    fontWeight: "600",
    marginTop: 2,
  },
  infoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 12,
  },
  infoCell: {
    backgroundColor: DESIGNER.pale,
    borderRadius: 12,
    minWidth: "47%",
    paddingHorizontal: 12,
    paddingVertical: 10,
    width: "47.5%",
  },
  infoCellWide: {
    backgroundColor: DESIGNER.pale,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    width: "100%",
  },
  infoLabel: {
    color: DESIGNER.muted,
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  infoValue: {
    color: DESIGNER.ink,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
    marginTop: 5,
  },
  timelineTargetPill: {
    backgroundColor: "rgba(201,168,106,0.16)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  timelineTargetText: {
    color: "#A8843E",
    fontSize: 10,
    fontWeight: "700",
  },
  timelineCard: {
    backgroundColor: DESIGNER.pale,
    borderRadius: 14,
    marginTop: 12,
    padding: 12,
  },
  timelineTop: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
  },
  timelineStatusPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  timelineStatusOnTrack: {
    backgroundColor: "rgba(47,93,80,0.12)",
  },
  timelineStatusOverdue: {
    backgroundColor: "rgba(251,44,54,0.12)",
  },
  timelineStatusDone: {
    backgroundColor: "rgba(201,168,106,0.18)",
  },
  timelineStatusText: {
    color: DESIGNER.accent,
    fontSize: 10,
    fontWeight: "700",
  },
  timelinePhaseLabel: {
    color: DESIGNER.ink,
    fontSize: 14,
    fontWeight: "700",
  },
  timelineMeta: {
    color: DESIGNER.muted,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 8,
  },
  itemCard: {
    backgroundColor: DESIGNER.pale,
    borderRadius: 14,
    marginTop: 10,
    padding: 12,
  },
  itemTitle: {
    color: DESIGNER.ink,
    fontSize: 14,
    fontWeight: "700",
  },
  itemMeta: {
    color: DESIGNER.muted,
    fontSize: 11,
    marginTop: 3,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: DESIGNER.accent,
    borderRadius: 12,
    justifyContent: "center",
    marginTop: 12,
    minHeight: 40,
    paddingHorizontal: 14,
  },
  primaryButtonText: {
    color: DESIGNER.white,
    fontSize: 12,
    fontWeight: "700",
  },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: DESIGNER.white,
    borderColor: DESIGNER.border,
    borderRadius: 12,
    borderWidth: 1,
    justifyContent: "center",
    marginTop: 12,
    minHeight: 40,
    paddingHorizontal: 14,
  },
  secondaryButtonText: {
    color: DESIGNER.ink,
    fontSize: 12,
    fontWeight: "700",
  },
  newChip: {
    backgroundColor: "rgba(47,93,80,0.1)",
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  newChipText: {
    color: DESIGNER.accent,
    fontSize: 11,
    fontWeight: "700",
  },
  formPanel: {
    backgroundColor: DESIGNER.white,
    borderColor: DESIGNER.border,
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 14,
    overflow: "hidden",
    padding: 14,
  },
  formPanelTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  formPanelTitle: {
    color: DESIGNER.ink,
    fontSize: 14,
    fontWeight: "700",
  },
  formField: {
    marginTop: 10,
  },
  formLabel: {
    color: DESIGNER.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.6,
    marginBottom: 6,
    textTransform: "uppercase",
  },
  formInput: {
    backgroundColor: DESIGNER.white,
    borderColor: DESIGNER.border,
    borderRadius: 10,
    borderWidth: 1,
    color: DESIGNER.ink,
    fontSize: 14,
    minHeight: 42,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  formTextArea: {
    minHeight: 78,
    textAlignVertical: "top",
  },
  formReadonly: {
    backgroundColor: DESIGNER.pale,
    color: DESIGNER.muted,
  },
  formRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 10,
  },
  formCol: {
    flexGrow: 1,
    minWidth: "30%",
  },
  formSelect: {
    alignItems: "center",
    backgroundColor: DESIGNER.white,
    borderColor: DESIGNER.border,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 42,
    paddingHorizontal: 12,
  },
  formSelectText: {
    color: DESIGNER.ink,
    flex: 1,
    fontSize: 14,
  },
  formChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  formChip: {
    backgroundColor: DESIGNER.pale,
    borderColor: DESIGNER.border,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  formChipActive: {
    backgroundColor: "rgba(47,93,80,0.12)",
    borderColor: "rgba(47,93,80,0.28)",
  },
  formChipText: {
    color: DESIGNER.muted,
    fontSize: 11,
    fontWeight: "600",
  },
  formChipTextActive: {
    color: DESIGNER.accent,
    fontWeight: "700",
  },
  createAreaButton: {
    alignItems: "center",
    backgroundColor: DESIGNER.gold,
    borderRadius: 12,
    justifyContent: "center",
    marginTop: 14,
    minHeight: 44,
  },
  createAreaButtonText: {
    color: DESIGNER.white,
    fontSize: 13,
    fontWeight: "700",
  },
  areaListHeader: {
    color: DESIGNER.muted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.3,
    marginTop: 16,
    textTransform: "uppercase",
  },
  galleryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  galleryTile: {
    aspectRatio: 1,
    backgroundColor: DESIGNER.pale,
    borderRadius: 12,
    overflow: "hidden",
    width: "47.5%",
  },
  galleryTileCaption: {
    backgroundColor: "rgba(44,36,32,0.72)",
    bottom: 0,
    left: 0,
    paddingHorizontal: 8,
    paddingVertical: 5,
    position: "absolute",
    right: 0,
  },
  galleryTileCaptionText: {
    color: DESIGNER.white,
    fontSize: 10,
    fontWeight: "600",
  },
  measureHeaderRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  measureHeaderIcon: {
    alignItems: "center",
    backgroundColor: "rgba(47,93,80,0.12)",
    borderRadius: 12,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  measureHeaderIconGold: {
    backgroundColor: "rgba(201,168,106,0.18)",
  },
  measureCard: {
    backgroundColor: DESIGNER.pale,
    borderColor: DESIGNER.border,
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 12,
    padding: 14,
  },
  measureCardTop: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
  },
  measureCardTitle: {
    color: DESIGNER.ink,
    fontFamily: "serif",
    fontSize: 16,
    fontWeight: "600",
    lineHeight: 20,
  },
  measureCardMeta: {
    color: DESIGNER.muted,
    fontSize: 11,
    marginTop: 4,
  },
  measureStatusPill: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  measureStatusConfirmed: {
    backgroundColor: "rgba(47,93,80,0.12)",
    borderColor: "rgba(47,93,80,0.22)",
  },
  measureStatusOther: {
    backgroundColor: DESIGNER.white,
    borderColor: DESIGNER.border,
  },
  measureStatusText: {
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  measureStatusTextConfirmed: {
    color: DESIGNER.accent,
  },
  measureStatusTextOther: {
    color: DESIGNER.muted,
  },
  measureActions: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  measureCaptureButton: {
    alignItems: "center",
    backgroundColor: DESIGNER.accent,
    borderRadius: 12,
    flex: 1,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    minHeight: 42,
    paddingHorizontal: 12,
  },
  measureCaptureText: {
    color: DESIGNER.white,
    fontSize: 12,
    fontWeight: "700",
  },
  measureUploadButton: {
    alignItems: "center",
    backgroundColor: DESIGNER.white,
    borderColor: "rgba(47,93,80,0.22)",
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    minHeight: 42,
    paddingHorizontal: 12,
  },
  measureUploadText: {
    color: DESIGNER.accent,
    fontSize: 12,
    fontWeight: "700",
  },
  measureEmpty: {
    alignItems: "center",
    backgroundColor: DESIGNER.pale,
    borderRadius: 14,
    marginTop: 12,
    paddingHorizontal: 16,
    paddingVertical: 22,
  },
  searchInput: {
    backgroundColor: DESIGNER.pale,
    borderRadius: 12,
    color: DESIGNER.ink,
    fontSize: 14,
    marginBottom: 8,
    marginTop: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  dividerBlock: {
    borderTopColor: DESIGNER.border,
    borderTopWidth: 1,
    marginTop: 12,
    paddingTop: 12,
  },
});
