import { StyleSheet } from "react-native";
import { DESIGNER } from "./designer.styles";

export const scheduleStyles = StyleSheet.create({
  scrollContent: {
    paddingBottom: 120,
  },
  hero: {
    backgroundColor: DESIGNER.charcoal,
    overflow: "hidden",
    paddingBottom: 18,
    paddingHorizontal: 19,
  },
  heroDecor: {
    backgroundColor: "rgba(47,93,80,0.4)",
    borderRadius: 999,
    height: 140,
    position: "absolute",
    right: -40,
    top: -50,
    width: 140,
  },
  brandMark: {
    color: "rgba(201,168,106,0.88)",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  heroTitle: {
    color: DESIGNER.white,
    fontFamily: "serif",
    fontSize: 28,
    fontWeight: "600",
    marginTop: 8,
  },
  heroSubtitle: {
    color: "rgba(255,255,255,0.42)",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 6,
  },
  body: {
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 14,
  },
  summary: {
    color: DESIGNER.muted,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  card: {
    backgroundColor: DESIGNER.white,
    borderColor: DESIGNER.border,
    borderRadius: 16,
    borderWidth: 1,
    overflow: "hidden",
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 14,
  },
  accent: {
    bottom: 0,
    left: 0,
    position: "absolute",
    top: 0,
    width: 3,
  },
  tagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 10,
  },
  tag: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  tagText: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.2,
    textTransform: "capitalize",
  },
  title: {
    color: DESIGNER.ink,
    fontFamily: "serif",
    fontSize: 17,
    fontWeight: "600",
    lineHeight: 22,
  },
  subtitle: {
    color: DESIGNER.muted,
    fontSize: 12,
    marginTop: 4,
  },
  metaList: {
    gap: 8,
    marginTop: 12,
  },
  metaRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
  },
  metaIcon: {
    alignItems: "center",
    backgroundColor: DESIGNER.pale,
    borderRadius: 10,
    height: 28,
    justifyContent: "center",
    marginTop: 1,
    width: 28,
  },
  metaCopy: {
    flex: 1,
    minWidth: 0,
  },
  metaLabel: {
    color: DESIGNER.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  metaValue: {
    color: DESIGNER.ink,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
    marginTop: 2,
  },
  detailsBox: {
    backgroundColor: DESIGNER.pale,
    borderRadius: 12,
    marginTop: 12,
    padding: 12,
  },
  detailsText: {
    color: DESIGNER.ink,
    fontSize: 13,
    lineHeight: 18,
  },
  detailsMuted: {
    color: DESIGNER.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  footerActions: {
    borderTopColor: DESIGNER.border,
    borderTopWidth: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 14,
    paddingTop: 14,
  },
  primaryBtn: {
    alignItems: "center",
    backgroundColor: DESIGNER.accent,
    borderRadius: 12,
    flexDirection: "row",
    flexGrow: 1,
    gap: 8,
    justifyContent: "center",
    minWidth: 140,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  primaryBtnDisabled: {
    opacity: 0.55,
  },
  primaryBtnText: {
    color: DESIGNER.white,
    fontSize: 13,
    fontWeight: "700",
  },
  secondaryBtn: {
    alignItems: "center",
    backgroundColor: DESIGNER.charcoal,
    borderRadius: 12,
    flexGrow: 1,
    justifyContent: "center",
    minWidth: 120,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  secondaryBtnText: {
    color: DESIGNER.white,
    fontSize: 13,
    fontWeight: "700",
  },
  centerState: {
    alignItems: "center",
    paddingVertical: 36,
  },
  centerMuted: {
    color: DESIGNER.muted,
    fontSize: 13,
    textAlign: "center",
  },
});
