import { StyleSheet } from "react-native";
import { DESIGNER } from "./designer.styles";

export const dashboardStyles = StyleSheet.create({
  hero: {
    backgroundColor: DESIGNER.charcoal,
    overflow: "hidden",
    paddingBottom: 22,
    paddingHorizontal: 19,
  },
  heroDecorLarge: {
    backgroundColor: "rgba(47,93,80,0.42)",
    borderRadius: 999,
    height: 180,
    position: "absolute",
    right: -48,
    top: -64,
    width: 180,
  },
  heroDecorMedium: {
    backgroundColor: "rgba(201,168,106,0.16)",
    borderRadius: 999,
    height: 110,
    left: -36,
    position: "absolute",
    top: 48,
    width: 110,
  },
  heroDecorSmall: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 999,
    height: 64,
    position: "absolute",
    right: 72,
    top: 18,
    width: 64,
  },
  heroTopRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  brandMark: {
    color: "rgba(201,168,106,0.88)",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  greetingLabel: {
    color: "rgba(255,255,255,0.48)",
    fontSize: 12,
    marginTop: 10,
  },
  heroTitle: {
    color: DESIGNER.white,
    fontFamily: "serif",
    fontSize: 28,
    fontWeight: "600",
    lineHeight: 34,
    marginTop: 2,
  },
  heroSubtitle: {
    color: "rgba(255,255,255,0.42)",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 6,
    maxWidth: 240,
  },
  heroActions: {
    flexDirection: "row",
    gap: 8,
    paddingTop: 2,
  },
  heroIconButton: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 17,
    height: 34,
    justifyContent: "center",
    position: "relative",
    width: 34,
  },
  heroAvatar: {
    alignItems: "center",
    backgroundColor: DESIGNER.accent,
    borderRadius: 17,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  heroAvatarText: {
    color: DESIGNER.white,
    fontFamily: "serif",
    fontSize: 11,
    fontWeight: "600",
  },
  badge: {
    alignItems: "center",
    backgroundColor: DESIGNER.red,
    borderRadius: 8,
    height: 16,
    justifyContent: "center",
    minWidth: 16,
    paddingHorizontal: 4,
    position: "absolute",
    right: -2,
    top: -2,
  },
  badgeText: {
    color: DESIGNER.white,
    fontSize: 9,
    fontWeight: "700",
  },
  heroDividerRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    marginTop: 18,
  },
  heroLine: {
    backgroundColor: "rgba(255,255,255,0.12)",
    flex: 1,
    height: 1,
  },
  heroPill: {
    alignItems: "center",
    backgroundColor: "rgba(47,93,80,0.35)",
    borderColor: "rgba(201,168,106,0.28)",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  heroPillDot: {
    backgroundColor: DESIGNER.gold,
    borderRadius: 3,
    height: 6,
    width: 6,
  },
  heroPillText: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.8,
  },
  body: {
    gap: 18,
    paddingBottom: 108,
    paddingHorizontal: 19,
    paddingTop: 16,
  },
  section: {
    gap: 10,
  },
  sectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  sectionLabel: {
    color: DESIGNER.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  sectionAction: {
    color: DESIGNER.accent,
    fontSize: 11,
    fontWeight: "700",
  },
  quickRow: {
    flexDirection: "row",
    gap: 10,
  },
  quickCard: {
    backgroundColor: DESIGNER.white,
    borderColor: DESIGNER.border,
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    minHeight: 92,
    overflow: "hidden",
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  quickCardPrimary: {
    backgroundColor: DESIGNER.accent,
    borderColor: DESIGNER.accent,
  },
  quickIconWrap: {
    alignItems: "center",
    backgroundColor: "rgba(47,93,80,0.1)",
    borderRadius: 10,
    height: 28,
    justifyContent: "center",
    marginBottom: 10,
    width: 28,
  },
  quickIconWrapPrimary: {
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  quickLabel: {
    color: DESIGNER.ink,
    fontSize: 13,
    fontWeight: "700",
  },
  quickLabelPrimary: {
    color: DESIGNER.white,
  },
  quickMeta: {
    color: DESIGNER.muted,
    fontSize: 11,
    lineHeight: 15,
    marginTop: 4,
  },
  quickMetaPrimary: {
    color: "rgba(255,255,255,0.68)",
  },
  metricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  metricCard: {
    backgroundColor: DESIGNER.white,
    borderColor: DESIGNER.border,
    borderRadius: 16,
    borderWidth: 1,
    minHeight: 92,
    overflow: "hidden",
    paddingHorizontal: 12,
    paddingVertical: 12,
    width: "48.5%",
  },
  metricAccent: {
    height: 3,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  metricIconRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  metricIcon: {
    alignItems: "center",
    borderRadius: 9,
    height: 26,
    justifyContent: "center",
    width: 26,
  },
  metricValue: {
    color: DESIGNER.ink,
    fontFamily: "serif",
    fontSize: 26,
    fontWeight: "600",
    lineHeight: 30,
  },
  metricLabel: {
    color: DESIGNER.muted,
    fontSize: 11,
    lineHeight: 14,
    marginTop: 4,
  },
  queueList: {
    gap: 10,
  },
  queueCard: {
    backgroundColor: DESIGNER.white,
    borderColor: DESIGNER.border,
    borderRadius: 16,
    borderWidth: 1,
    overflow: "hidden",
    paddingLeft: 14,
    paddingRight: 14,
    paddingVertical: 14,
  },
  queueAccent: {
    bottom: 0,
    left: 0,
    position: "absolute",
    top: 0,
    width: 3,
  },
  queueTop: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
  },
  queueCopy: {
    flex: 1,
    minWidth: 0,
  },
  queueTitle: {
    color: DESIGNER.ink,
    fontSize: 14,
    fontWeight: "700",
  },
  queueMeta: {
    color: DESIGNER.muted,
    fontSize: 11,
    marginTop: 3,
  },
  priorityBadge: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  priorityText: {
    color: DESIGNER.white,
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  queueActionLabel: {
    color: DESIGNER.muted,
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.5,
    marginTop: 12,
    textTransform: "uppercase",
  },
  queueActionText: {
    color: DESIGNER.ink,
    fontSize: 13,
    fontWeight: "500",
    lineHeight: 18,
    marginTop: 4,
  },
  queueFooter: {
    alignItems: "center",
    borderTopColor: DESIGNER.border,
    borderTopWidth: 1,
    flexDirection: "row",
    gap: 8,
    justifyContent: "space-between",
    marginTop: 12,
    paddingTop: 12,
  },
  openHint: {
    color: DESIGNER.accent,
    fontSize: 11,
    fontWeight: "700",
  },
  emptyState: {
    alignItems: "center",
    backgroundColor: DESIGNER.white,
    borderColor: DESIGNER.border,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 24,
  },
  emptyTitle: {
    color: DESIGNER.ink,
    fontFamily: "serif",
    fontSize: 16,
    fontWeight: "600",
  },
  emptyText: {
    color: DESIGNER.muted,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 6,
    textAlign: "center",
  },
  chipsWrap: {
    marginHorizontal: -19,
  },
  projectsChipsWrap: {
    paddingTop: 4,
  },
  projectsSearch: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.1)",
    borderColor: "rgba(255,255,255,0.12)",
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    marginTop: 16,
    minHeight: 44,
    paddingHorizontal: 14,
  },
  projectsSearchInput: {
    color: DESIGNER.white,
    flex: 1,
    fontSize: 14,
    paddingVertical: 10,
  },
  projectsBody: {
    gap: 12,
    paddingBottom: 108,
    paddingHorizontal: 19,
    paddingTop: 14,
  },
  projectsSummary: {
    color: DESIGNER.muted,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  projectCard: {
    backgroundColor: DESIGNER.white,
    borderColor: DESIGNER.border,
    borderRadius: 16,
    borderWidth: 1,
    overflow: "hidden",
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 14,
  },
  projectAccent: {
    bottom: 0,
    left: 0,
    position: "absolute",
    top: 0,
    width: 3,
  },
  projectTop: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
  },
  projectCopy: {
    flex: 1,
    minWidth: 0,
  },
  projectCode: {
    color: DESIGNER.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  projectName: {
    color: DESIGNER.ink,
    fontFamily: "serif",
    fontSize: 17,
    fontWeight: "600",
    lineHeight: 22,
    marginTop: 4,
  },
  projectType: {
    color: DESIGNER.muted,
    fontSize: 11,
    marginTop: 4,
  },
  projectChevron: {
    alignItems: "center",
    backgroundColor: DESIGNER.pale,
    borderRadius: 12,
    height: 28,
    justifyContent: "center",
    marginTop: 2,
    width: 28,
  },
  projectFooter: {
    alignItems: "center",
    borderTopColor: DESIGNER.border,
    borderTopWidth: 1,
    flexDirection: "row",
    gap: 8,
    justifyContent: "space-between",
    marginTop: 12,
    paddingTop: 12,
  },
  statusPill: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  statusPillText: {
    fontSize: 10,
    fontWeight: "700",
  },
  projectTarget: {
    color: DESIGNER.muted,
    flexShrink: 1,
    fontSize: 11,
    textAlign: "right",
  },

  messagesBody: {
    gap: 12,
    paddingBottom: 108,
    paddingHorizontal: 19,
    paddingTop: 14,
  },
  messagesSummary: {
    color: DESIGNER.muted,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  messagesPicker: {
    backgroundColor: DESIGNER.white,
    borderColor: DESIGNER.border,
    borderRadius: 16,
    borderWidth: 1,
    overflow: "hidden",
  },
  messagesPickerTrigger: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  messagesPickerTriggerOpen: {
    borderBottomColor: DESIGNER.border,
    borderBottomWidth: 1,
  },
  messagesPickerIcon: {
    alignItems: "center",
    backgroundColor: "rgba(47,93,80,0.12)",
    borderRadius: 12,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  messagesPickerLabel: {
    color: DESIGNER.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  messagesPickerValue: {
    color: DESIGNER.ink,
    fontFamily: "serif",
    fontSize: 16,
    fontWeight: "600",
    lineHeight: 20,
    marginTop: 3,
  },
  messagesPickerMeta: {
    color: DESIGNER.muted,
    fontSize: 11,
    marginTop: 3,
  },
  messagesPickerChevron: {
    alignItems: "center",
    backgroundColor: DESIGNER.pale,
    borderRadius: 12,
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  messagesPickerMenu: {
    maxHeight: 220,
  },
  messagesPickerOption: {
    alignItems: "center",
    borderTopColor: DESIGNER.border,
    borderTopWidth: 1,
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  messagesPickerOptionSelected: {
    backgroundColor: "rgba(47,93,80,0.06)",
  },
  messagesPickerOptionText: {
    color: DESIGNER.ink,
    fontSize: 13,
    fontWeight: "600",
  },
  messagesPickerOptionMeta: {
    color: DESIGNER.muted,
    fontSize: 11,
    marginTop: 2,
  },
  messagesPickerCheck: {
    color: DESIGNER.accent,
    fontSize: 14,
    fontWeight: "700",
  },
  messageCard: {
    backgroundColor: DESIGNER.white,
    borderColor: DESIGNER.border,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    overflow: "hidden",
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 14,
  },
  messageAccent: {
    bottom: 0,
    left: 0,
    position: "absolute",
    top: 0,
    width: 3,
  },
  messageAccentDesigner: {
    backgroundColor: DESIGNER.accent,
  },
  messageAccentSales: {
    backgroundColor: DESIGNER.gold,
  },
  messageAvatar: {
    alignItems: "center",
    borderRadius: 22,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  messageAvatarText: {
    color: DESIGNER.white,
    fontFamily: "serif",
    fontSize: 13,
    fontWeight: "600",
  },
  messageBody: {
    flex: 1,
    minWidth: 0,
  },
  messageTop: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
  },
  messageTitle: {
    color: DESIGNER.ink,
    flex: 1,
    fontFamily: "serif",
    fontSize: 16,
    fontWeight: "600",
    lineHeight: 20,
  },
  messageTime: {
    color: DESIGNER.muted,
    fontSize: 10,
    marginTop: 3,
  },
  messagePreview: {
    color: "#5C534E",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 6,
  },
  messageFooter: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    justifyContent: "space-between",
    marginTop: 10,
  },
  messageTypePill: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  messageTypePillDesigner: {
    backgroundColor: "rgba(47,93,80,0.1)",
    borderColor: "rgba(47,93,80,0.18)",
  },
  messageTypePillSales: {
    backgroundColor: "rgba(201,168,106,0.16)",
    borderColor: "rgba(201,168,106,0.28)",
  },
  messageTypeText: {
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  messageTypeTextDesigner: {
    color: DESIGNER.accent,
  },
  messageTypeTextSales: {
    color: "#A8843E",
  },
  messageStatus: {
    color: DESIGNER.muted,
    fontSize: 10,
    fontWeight: "600",
  },
});
