import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: "#FAF8F5",
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 32,
  },
  heroSection: {
    backgroundColor: "#1A1614",
    height: 200,
    overflow: "hidden",
    position: "relative",
  },
  heroDecorLarge: {
    backgroundColor: "rgba(201,168,106,0.08)",
    borderRadius: 999,
    height: 170,
    position: "absolute",
    right: -60,
    top: -70,
    width: 170,
  },
  heroDecorSmall: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 999,
    bottom: 32,
    height: 90,
    left: -40,
    position: "absolute",
    width: 90,
  },
  heroContent: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    paddingBottom: 22,
    paddingHorizontal: 24,
    paddingTop: 12,
    zIndex: 1,
  },
  heroLogoFrame: {
    backgroundColor: "#0E0C0B",
    borderColor: "rgba(201,168,106,0.45)",
    borderRadius: 20,
    borderWidth: 1,
    height: 104,
    overflow: "hidden",
    width: 104,
  },
  heroLogo: {
    height: "100%",
    transform: [{ scale: 1.34 }],
    width: "100%",
  },
  heroTagline: {
    color: "rgba(201,168,106,0.72)",
    fontSize: 9,
    fontWeight: "600",
    letterSpacing: 1.2,
    marginTop: 10,
  },
  heroCurve: {
    backgroundColor: "#FAF8F5",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    bottom: -1,
    height: 24,
    left: 0,
    position: "absolute",
    right: 0,
    zIndex: 2,
  },
  formSection: {
    paddingHorizontal: 22,
    paddingTop: 8,
  },
  title: {
    color: "#2C2420",
    fontFamily: "serif",
    fontSize: 28,
    letterSpacing: -0.2,
  },
  subtitle: {
    color: "#7A6F68",
    fontSize: 13,
    lineHeight: 20,
    marginTop: 4,
  },
  fieldSection: {
    marginTop: 14,
  },
  label: {
    color: "#7A6F68",
    fontSize: 10,
    fontWeight: "600",
    letterSpacing: 1,
  },
  inputWrap: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(60,51,48,0.08)",
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: "row",
    height: 48,
    marginTop: 7,
    paddingHorizontal: 15,
  },
  input: {
    color: "#2C2420",
    flex: 1,
    fontSize: 13,
    marginLeft: 11,
    paddingVertical: 0,
  },
  passwordHint: {
    color: "rgba(122,111,104,0.65)",
    fontSize: 10,
    lineHeight: 15,
    marginTop: 6,
  },
  fieldError: {
    color: "#C23B3B",
    fontSize: 11,
    lineHeight: 15,
    marginTop: 6,
  },
  inputWrapError: {
    borderColor: "#E24B4A",
    borderWidth: 1.5,
  },
  button: {
    alignItems: "center",
    backgroundColor: "#3A3330",
    borderRadius: 14,
    height: 48,
    justifyContent: "center",
    marginTop: 18,
    width: "100%",
  },
  buttonPressed: {
    opacity: 0.92,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  footerRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 22,
  },
  footerText: {
    color: "#7A6F68",
    fontSize: 13,
  },
  footerLink: {
    color: "#C9A86A",
    fontSize: 13,
    fontWeight: "700",
  },
});
