import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: "#FAF8F5",
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  heroSection: {
    backgroundColor: "#1A1614",
    height: 220,
    overflow: "hidden",
    position: "relative",
  },
  heroDecorLarge: {
    backgroundColor: "rgba(201,168,106,0.08)",
    borderRadius: 999,
    height: 180,
    position: "absolute",
    right: -70,
    top: -80,
    width: 180,
  },
  heroDecorSmall: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 999,
    bottom: 36,
    height: 100,
    left: -50,
    position: "absolute",
    width: 100,
  },
  heroContent: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    paddingBottom: 24,
    paddingHorizontal: 24,
    paddingTop: 14,
    zIndex: 1,
  },
  heroLogoFrame: {
    backgroundColor: "#0E0C0B",
    borderColor: "rgba(201,168,106,0.45)",
    borderRadius: 20,
    borderWidth: 1,
    height: 112,
    overflow: "hidden",
    width: 112,
  },
  heroLogo: {
    height: "100%",
    transform: [{ scale: 1.34 }],
    width: "100%",
  },
  heroTagline: {
    color: "rgba(201,168,106,0.72)",
    fontSize: 8,
    fontWeight: "600",
    letterSpacing: 0.6,
    marginTop: 10,
    paddingHorizontal: 16,
    textAlign: "center",
  },
  heroCurve: {
    backgroundColor: "#FAF8F5",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    bottom: -1,
    height: 24,
    left: 0,
    position: "absolute",
    right: 0,
    zIndex: 2,
  },
  formSection: {
    paddingBottom: 28,
    paddingHorizontal: 22,
    paddingTop: 8,
  },
  title: {
    color: "#2C2420",
    fontFamily: "serif",
    fontSize: 30,
    letterSpacing: -0.2,
  },
  subtitle: {
    color: "#7A6F68",
    fontSize: 13,
    marginTop: 4,
  },
  fieldSection: {
    marginTop: 16,
  },
  label: {
    color: "#7A6F68",
    fontSize: 10,
    fontWeight: "600",
    letterSpacing: 1,
  },
  inputWrap: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(60,51,48,0.08)",
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: "row",
    height: 48,
    marginTop: 7,
    paddingHorizontal: 15,
  },
  input: {
    color: "#2C2420",
    flex: 1,
    fontSize: 13,
    marginLeft: 11,
  },
  passwordRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  forgotText: {
    color: "#C9A86A",
    fontSize: 11,
    fontWeight: "600",
  },
  button: {
    alignItems: "center",
    backgroundColor: "#3A3330",
    borderRadius: 14,
    height: 48,
    justifyContent: "center",
    marginTop: 18,
    width: "100%",
  },
  buttonPressed: {
    opacity: 0.92,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  contactRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 22,
  },
  contactText: {
    color: "#7A6F68",
    fontSize: 13,
  },
  contactAction: {
    color: "#C9A86A",
    fontSize: 13,
    fontWeight: "700",
  },
  copyright: {
    color: "rgba(122,111,104,0.4)",
    fontSize: 10,
    letterSpacing: 1,
    marginTop: 22,
    textAlign: "center",
  },
});
