import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: { backgroundColor: "#FAF8F5", flex: 1 },
  header: {
    alignItems: "center",
    backgroundColor: "#3A3330",
    flexDirection: "row",
    paddingHorizontal: 15,
    paddingTop: 38,
    paddingBottom: 11,
  },
  headerCircleButton: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 14,
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  headerMeta: { flex: 1, marginHorizontal: 11 },
  headerName: { color: "#FFFFFF", fontSize: 13 },
  headerStatusRow: { alignItems: "center", flexDirection: "row", marginTop: 2 },
  onlineDot: { backgroundColor: "#10B981", borderRadius: 3, height: 6, width: 6 },
  headerStatus: { color: "rgba(255,255,255,0.6)", fontSize: 10, marginLeft: 6 },
  chatBody: { flex: 1 },
  chatContent: { paddingHorizontal: 15, paddingTop: 11, paddingBottom: 12 },
  dayDivider: { alignItems: "center", flexDirection: "row", marginBottom: 10 },
  dividerLine: { backgroundColor: "rgba(122,111,104,0.2)", flex: 1, height: 1 },
  dividerText: { color: "#7A6F68", fontSize: 10, marginHorizontal: 8 },
  senderLabel: { color: "#7A6F68", fontSize: 10, marginBottom: 5 },
  incomingBubble: {
    alignSelf: "flex-start",
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(60,51,48,0.05)",
    borderRadius: 12,
    borderWidth: 1,
    maxWidth: "75%",
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  incomingText: { color: "#2C2420", fontSize: 13, lineHeight: 20 },
  outgoingWrap: { alignItems: "flex-end", marginTop: 8 },
  outgoingBubble: {
    backgroundColor: "#3A3330",
    borderRadius: 12,
    maxWidth: "75%",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  outgoingText: { color: "#FFFFFF", fontSize: 13, lineHeight: 20 },
  timeLeft: { color: "#7A6F68", fontSize: 10, marginTop: 4 },
  timeRight: { alignSelf: "flex-end", color: "#7A6F68", fontSize: 10, marginTop: 4 },
  mt12: { marginTop: 12 },
  filePreview: {
    alignItems: "center",
    backgroundColor: "#F5F2ED",
    borderRadius: 9,
    flexDirection: "row",
    marginBottom: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  fileName: { color: "#7A6F68", fontSize: 11, marginLeft: 6 },
  fileMessage: { marginTop: 0 },
  composer: {
    alignItems: "center",
    backgroundColor: "#FAF8F5",
    borderTopColor: "rgba(60,51,48,0.08)",
    borderTopWidth: 1,
    flexDirection: "row",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  composerIconButton: {
    alignItems: "center",
    backgroundColor: "#F5F2ED",
    borderRadius: 13,
    height: 26,
    justifyContent: "center",
    width: 26,
  },
  composerInput: {
    backgroundColor: "#F5F2ED",
    borderRadius: 13,
    color: "#2C2420",
    flex: 1,
    fontSize: 12,
    height: 30,
    marginHorizontal: 8,
    paddingHorizontal: 11,
  },
  sendButton: {
    alignItems: "center",
    backgroundColor: "#C9A86A",
    borderRadius: 13,
    height: 26,
    justifyContent: "center",
    width: 26,
  },
  bottomNav: {
    backgroundColor: "rgba(255,255,255,0.95)",
    borderTopColor: "rgba(60,51,48,0.08)",
    borderTopWidth: 1,
    flexDirection: "row",
    height: 62,
  },
  bottomItem: { alignItems: "center", flex: 1, justifyContent: "center" },
  bottomIconWrap: { position: "relative" },
  bottomBadge: {
    alignItems: "center",
    backgroundColor: "#C9A86A",
    borderRadius: 8,
    height: 15,
    justifyContent: "center",
    minWidth: 15,
    paddingHorizontal: 4,
    position: "absolute",
    right: -10,
    top: -5,
  },
  bottomBadgeText: { color: "#FFFFFF", fontSize: 9 },
  bottomLabel: { color: "rgba(122,111,104,0.7)", fontSize: 10, marginTop: 4 },
  bottomLabelActive: { color: "#C9A86A" },
  bottomActiveIndicator: {
    backgroundColor: "#C9A86A",
    borderRadius: 999,
    height: 2,
    position: "absolute",
    top: 3,
    width: 20,
  },
});
