import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: "#FAF8F5",
    flex: 1,
  },
  keyboardAvoid: {
    flex: 1,
  },
  chatArea: {
    flex: 1,
  },
  header: {
    alignItems: "center",
    backgroundColor: "#3A3330",
    borderBottomColor: "rgba(201,168,106,0.2)",
    borderBottomWidth: 1,
    flexDirection: "row",
    paddingBottom: 14,
    paddingHorizontal: 15,
    paddingTop: 38,
  },
  headerCircleButton: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 16,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  headerAvatar: {
    alignItems: "center",
    backgroundColor: "#C9A86A",
    borderColor: "rgba(255,255,255,0.25)",
    borderRadius: 20,
    borderWidth: 2,
    height: 40,
    justifyContent: "center",
    marginHorizontal: 10,
    width: 40,
  },
  headerAvatarText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
  },
  headerMeta: {
    flex: 1,
  },
  headerName: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
  },
  headerStatusRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 4,
  },
  statusPill: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  statusPillOpen: {
    backgroundColor: "rgba(16,185,129,0.22)",
  },
  statusPillClosed: {
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  statusPillText: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 9,
    fontWeight: "600",
  },
  statusPillTextOpen: {
    color: "#A7F3D0",
  },
  onlineDot: {
    backgroundColor: "#10B981",
    borderRadius: 4,
    height: 7,
    width: 7,
  },
  headerStatus: {
    color: "rgba(255,255,255,0.6)",
    flexShrink: 1,
    fontSize: 10,
  },
  chatList: {
    backgroundColor: "#F7F4EE",
    flex: 1,
  },
  chatContent: {
    paddingBottom: 12,
    paddingHorizontal: 16,
    paddingTop: 14,
  },
  messageBlock: {
    marginBottom: 12,
  },
  senderLabel: {
    color: "#7A6F68",
    fontSize: 10,
    fontWeight: "600",
    marginBottom: 5,
    marginLeft: 6,
  },
  incomingBubble: {
    alignSelf: "flex-start",
    backgroundColor: "#FFFFFF",
    borderBottomLeftRadius: 6,
    borderColor: "rgba(60,51,48,0.07)",
    borderRadius: 18,
    borderWidth: 1,
    maxWidth: "80%",
    overflow: "hidden",
    paddingHorizontal: 13,
    paddingVertical: 11,
    ...Platform.select({
      ios: {
        shadowColor: "#3A3330",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 6,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  incomingText: {
    color: "#2C2420",
    fontSize: 14,
    lineHeight: 21,
  },
  outgoingWrap: {
    alignItems: "flex-end",
    marginBottom: 12,
  },
  outgoingBubble: {
    backgroundColor: "#3A3330",
    borderBottomRightRadius: 6,
    borderRadius: 18,
    maxWidth: "80%",
    overflow: "hidden",
    paddingHorizontal: 14,
    paddingVertical: 11,
    position: "relative",
    ...Platform.select({
      ios: {
        shadowColor: "#3A3330",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 6,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  outgoingAccent: {
    backgroundColor: "#C9A86A",
    bottom: 0,
    left: 0,
    position: "absolute",
    top: 0,
    width: 3,
  },
  outgoingText: {
    color: "#FFFFFF",
    fontSize: 14,
    lineHeight: 21,
  },
  timeLeft: {
    color: "rgba(122,111,104,0.55)",
    fontSize: 9,
    letterSpacing: 0.3,
    marginLeft: 6,
    marginTop: 5,
  },
  timeRight: {
    alignSelf: "flex-end",
    color: "rgba(122,111,104,0.55)",
    fontSize: 9,
    letterSpacing: 0.3,
    marginRight: 6,
    marginTop: 5,
  },
  filePreview: {
    alignItems: "center",
    backgroundColor: "rgba(245,242,237,0.95)",
    borderColor: "rgba(60,51,48,0.08)",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    marginBottom: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  fileIconWrap: {
    alignItems: "center",
    backgroundColor: "rgba(201,168,106,0.15)",
    borderRadius: 8,
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  fileName: {
    color: "#2C2420",
    flex: 1,
    fontSize: 11,
    fontWeight: "500",
    marginLeft: 8,
  },
  closedBanner: {
    backgroundColor: "rgba(201,168,106,0.18)",
    borderBottomColor: "rgba(201,168,106,0.28)",
    borderBottomWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  closedBannerText: {
    color: "#7A6F68",
    fontSize: 11,
    lineHeight: 16,
    textAlign: "center",
  },
  centerState: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  emptyThreadState: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 32,
    paddingVertical: 40,
  },
  emptyThreadTitle: {
    color: "#2C2420",
    fontSize: 15,
    fontWeight: "600",
    textAlign: "center",
  },
  emptyThreadText: {
    color: "#7A6F68",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 6,
    textAlign: "center",
  },
  errorText: {
    color: "#7A6F68",
    fontSize: 13,
    lineHeight: 20,
    textAlign: "center",
  },
  loadMoreState: {
    alignItems: "center",
    paddingVertical: 12,
  },
  deletedWrap: {
    alignItems: "center",
    marginVertical: 8,
  },
  deletedText: {
    backgroundColor: "rgba(122,111,104,0.08)",
    borderRadius: 999,
    color: "rgba(122,111,104,0.65)",
    fontSize: 10,
    fontStyle: "italic",
    overflow: "hidden",
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  systemWrap: {
    alignItems: "center",
    marginVertical: 10,
  },
  systemText: {
    backgroundColor: "rgba(201,168,106,0.15)",
    borderRadius: 999,
    color: "#7A6F68",
    fontSize: 10,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  composerWrap: {
    backgroundColor: "#FFFFFF",
    borderTopColor: "rgba(60,51,48,0.08)",
    borderTopWidth: 1,
    paddingHorizontal: 12,
    paddingTop: 10,
    ...Platform.select({
      ios: {
        shadowColor: "#3A3330",
        shadowOffset: { width: 0, height: -3 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
      },
      android: {
        elevation: 10,
      },
    }),
  },
  composer: {
    alignItems: "flex-end",
    flexDirection: "row",
    gap: 8,
  },
  composerDisabled: {
    opacity: 0.5,
  },
  composerIconButton: {
    alignItems: "center",
    backgroundColor: "#F5F2ED",
    borderColor: "rgba(60,51,48,0.06)",
    borderRadius: 20,
    borderWidth: 1,
    height: 40,
    justifyContent: "center",
    marginBottom: 1,
    width: 40,
  },
  composerInputWrap: {
    backgroundColor: "#F5F2ED",
    borderColor: "rgba(60,51,48,0.08)",
    borderRadius: 20,
    borderWidth: 1,
    flex: 1,
    minHeight: 40,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === "ios" ? 9 : 6,
  },
  composerInput: {
    color: "#2C2420",
    fontSize: 14,
    lineHeight: 20,
    maxHeight: 96,
    minHeight: 20,
    padding: 0,
  },
  sendButton: {
    alignItems: "center",
    backgroundColor: "#C9A86A",
    borderRadius: 20,
    height: 40,
    justifyContent: "center",
    marginBottom: 1,
    width: 40,
  },
  sendButtonDisabled: {
    backgroundColor: "rgba(201,168,106,0.45)",
  },
});
