import { Platform, StyleSheet } from "react-native";

export const SALE = {
  bg: "#FAF8F5",
  charcoal: "#3A3330",
  ink: "#2C2420",
  gold: "#C9A86A",
  muted: "#7A6F68",
  pale: "#F5F2ED",
  white: "#FFFFFF",
  border: "rgba(60,51,48,0.06)",
  red: "#FB2C36",
} as const;

export const saleStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: SALE.bg, alignItems: "center" },
  frame: {
    flex: 1,
    width: "100%",
    maxWidth: 420,
    backgroundColor: SALE.bg,
    ...Platform.select({ web: { boxShadow: "0 4px 40px rgba(0,0,0,.08)" } as object }),
  },
  fill: { flex: 1 },
  header: { backgroundColor: SALE.charcoal, paddingHorizontal: 19, paddingBottom: 15 },
  headerEyebrow: { color: "rgba(255,255,255,.5)", fontSize: 10, letterSpacing: 1, textTransform: "uppercase" },
  headerTitle: { color: SALE.white, fontFamily: "serif", fontSize: 20, fontWeight: "600", lineHeight: 28 },
  headerSubtitle: { color: "rgba(255,255,255,.42)", fontSize: 10, marginTop: 2 },
  headerRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  headerIcon: { width: 34, height: 34, borderRadius: 17, backgroundColor: "rgba(255,255,255,.1)", alignItems: "center", justifyContent: "center" },
  avatarGold: { width: 34, height: 34, borderRadius: 17, backgroundColor: SALE.gold, alignItems: "center", justifyContent: "center" },
  avatarText: { color: SALE.white, fontFamily: "serif", fontSize: 11, fontWeight: "600" },
  headerActions: { flexDirection: "row", gap: 8 },
  searchRow: { flexDirection: "row", gap: 8, marginTop: 15 },
  search: { flex: 1, height: 38, borderRadius: 15, backgroundColor: "rgba(255,255,255,.1)", flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 12 },
  searchInput: { flex: 1, color: SALE.white, fontSize: 13, paddingVertical: 0 },
  searchLight: { height: 40, borderRadius: 15, backgroundColor: SALE.pale, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 12 },
  filterButton: { width: 38, height: 38, borderRadius: 15, backgroundColor: "rgba(255,255,255,.1)", alignItems: "center", justifyContent: "center" },
  chips: { paddingHorizontal: 19, paddingVertical: 12, gap: 8 },
  chip: { height: 28, borderRadius: 15, backgroundColor: SALE.pale, paddingHorizontal: 12, alignItems: "center", justifyContent: "center" },
  chipActive: { backgroundColor: SALE.charcoal },
  chipText: { color: SALE.muted, fontSize: 11, fontWeight: "500" },
  chipTextActive: { color: SALE.white },
  content: { paddingHorizontal: 19, paddingTop: 8, paddingBottom: 100 },
  contentGap: { gap: 12 },
  sectionRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 11 },
  sectionLabel: { color: SALE.muted, fontSize: 10, letterSpacing: 1, textTransform: "uppercase" },
  sectionAction: { color: SALE.gold, fontSize: 10, fontWeight: "600" },
  card: { backgroundColor: SALE.white, borderWidth: 1, borderColor: SALE.border, borderRadius: 15, padding: 15 },
  cardTitle: { color: SALE.ink, fontFamily: "serif", fontSize: 14, lineHeight: 19 },
  cardMeta: { color: SALE.muted, fontFamily: "monospace", fontSize: 10, marginTop: 2 },
  topCardRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 8 },
  status: { borderRadius: 20, paddingHorizontal: 8, paddingVertical: 3, backgroundColor: "#FFFBEB", borderWidth: 1, borderColor: "#FEE685", maxWidth: 145 },
  statusText: { color: "#BB4D00", fontSize: 9 },
  priorityDot: { width: 8, height: 8, borderRadius: 4, marginRight: 8, marginTop: 5 },
  infoGrid: { flexDirection: "row", flexWrap: "wrap", rowGap: 9, marginTop: 12 },
  infoCell: { width: "50%" },
  infoLabel: { color: SALE.muted, fontSize: 9, letterSpacing: .3, textTransform: "uppercase" },
  infoValue: { color: SALE.ink, fontSize: 11, marginTop: 2 },
  buttonRow: { flexDirection: "row", gap: 8, marginTop: 12, paddingTop: 8, borderTopWidth: 1, borderTopColor: SALE.border },
  buttonSecondary: { flex: 1, height: 31, borderRadius: 15, backgroundColor: SALE.pale, alignItems: "center", justifyContent: "center" },
  buttonPrimary: { flex: 1, height: 31, borderRadius: 15, backgroundColor: SALE.charcoal, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 5 },
  buttonSecondaryText: { color: SALE.muted, fontSize: 11, fontWeight: "600" },
  buttonPrimaryText: { color: SALE.white, fontSize: 11, fontWeight: "600" },
  nav: { backgroundColor: SALE.white, borderTopWidth: 1, borderTopColor: SALE.border, flexDirection: "row", minHeight: 58 },
  navFixed: { position: "absolute", left: 0, right: 0, bottom: 0 },
  navItem: { flex: 1, alignItems: "center", justifyContent: "center", paddingTop: 9, gap: 3 },
  navIcon: { height: 22, justifyContent: "center" },
  navLabel: { fontSize: 9, color: SALE.muted, letterSpacing: .35, textTransform: "uppercase", fontWeight: "500" },
  navLabelActive: { color: SALE.charcoal },
  navIndicator: { position: "absolute", top: 0, width: 30, height: 2, borderBottomLeftRadius: 9, borderBottomRightRadius: 9, backgroundColor: SALE.gold },
  badge: { position: "absolute", right: -8, top: -5, minWidth: 15, height: 15, borderRadius: 8, backgroundColor: SALE.red, alignItems: "center", justifyContent: "center", paddingHorizontal: 3 },
  badgeText: { color: SALE.white, fontSize: 8, fontWeight: "700" },
  alertScroller: { paddingHorizontal: 19, gap: 11 },
  alertCard: { width: 188, height: 132, backgroundColor: SALE.white, borderRadius: 15, padding: 13, borderWidth: 1, borderLeftWidth: 4 },
  alertTop: { flexDirection: "row", justifyContent: "space-between" },
  alertIcon: { width: 27, height: 27, borderRadius: 14, alignItems: "center", justifyContent: "center" },
  priorityBadge: { borderRadius: 20, paddingHorizontal: 6, paddingVertical: 2 },
  priorityText: { color: SALE.white, fontSize: 9, fontWeight: "700", textTransform: "uppercase" },
  alertTitle: { color: SALE.ink, fontSize: 12, fontWeight: "600", marginTop: 10 },
  alertDescription: { color: SALE.muted, fontSize: 10, marginTop: 4 },
  metricGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  metric: { width: "48.8%", backgroundColor: SALE.white, borderWidth: 1, borderColor: SALE.border, borderRadius: 15, padding: 11 },
  metricRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end" },
  metricValue: { fontFamily: "serif", fontSize: 26 },
  metricDelta: { color: "#009966", fontSize: 10 },
  metricLabel: { color: SALE.muted, fontSize: 10, marginTop: 2 },
  pipeline: { backgroundColor: SALE.white, borderRadius: 15, padding: 15, borderWidth: 1, borderColor: SALE.border },
  pipelineRow: { flexDirection: "row", alignItems: "center", marginTop: 11 },
  pipelineLabel: { width: 82, color: SALE.muted, fontSize: 10 },
  pipelineTrack: { flex: 1, height: 8, borderRadius: 4, backgroundColor: SALE.pale, overflow: "hidden" },
  pipelineFill: { height: 8, borderRadius: 4, backgroundColor: SALE.gold },
  pipelineCount: { width: 24, textAlign: "right", color: SALE.ink, fontSize: 10 },
  commercial: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  commercialValue: { fontFamily: "serif", fontSize: 22, color: SALE.ink },
  commercialLabel: { color: SALE.muted, fontSize: 9, textTransform: "uppercase", marginTop: 2 },
  dividerVertical: { width: 1, height: 34, backgroundColor: SALE.border },
  conversation: { backgroundColor: SALE.white, borderRadius: 15, borderWidth: 1, borderColor: SALE.border, padding: 15, flexDirection: "row", gap: 13 },
  roundAvatar: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center" },
  online: { position: "absolute", right: 0, bottom: 0, width: 11, height: 11, borderRadius: 6, backgroundColor: "#00BC7D", borderWidth: 2, borderColor: SALE.white },
  conversationBody: { flex: 1 },
  conversationTop: { flexDirection: "row", justifyContent: "space-between" },
  conversationName: { color: SALE.ink, fontSize: 13, fontWeight: "600" },
  conversationMeta: { color: SALE.muted, fontSize: 10, marginTop: 1 },
  conversationTime: { color: SALE.muted, fontSize: 10 },
  conversationPreview: { color: SALE.muted, fontSize: 11, marginTop: 7 },
  unread: { alignSelf: "flex-end", marginTop: 6, width: 19, height: 19, borderRadius: 10, backgroundColor: SALE.gold, alignItems: "center", justifyContent: "center" },
  detailHeaderTop: { flexDirection: "row", gap: 11, alignItems: "center" },
  backButton: { width: 30, height: 30, borderRadius: 15, backgroundColor: "rgba(255,255,255,.1)", alignItems: "center", justifyContent: "center" },
  detailTitleWrap: { flex: 1 },
  detailCode: { color: "rgba(255,255,255,.5)", fontSize: 10, letterSpacing: .8 },
  detailTitle: { color: SALE.white, fontFamily: "serif", fontSize: 16.5, fontWeight: "600" },
  progress: { flexDirection: "row", alignItems: "center", marginTop: 15 },
  progressDot: { width: 15, height: 15, borderRadius: 8, borderWidth: 2, borderColor: "rgba(255,255,255,.25)" },
  progressDone: { backgroundColor: "#00BC7D", borderColor: "#00BC7D" },
  progressCurrent: { backgroundColor: "rgba(201,168,106,.2)", borderColor: SALE.gold },
  progressLine: { flex: 1, height: 1, backgroundColor: "rgba(255,255,255,.15)" },
  progressLineDone: { backgroundColor: "rgba(0,212,146,.6)" },
  progressLabel: { color: "rgba(255,255,255,.5)", fontSize: 10, marginTop: 6 },
  progressGold: { color: SALE.gold },
  tabs: { paddingHorizontal: 19, paddingVertical: 11, gap: 8, borderBottomWidth: 1, borderBottomColor: SALE.border },
  alert: { backgroundColor: "#FFFBEB", borderColor: "#FEE685", borderWidth: 1, borderRadius: 15, padding: 15, flexDirection: "row", gap: 11 },
  alertCopy: { flex: 1 },
  alertHeading: { color: "#BB4D00", fontSize: 11, fontWeight: "600" },
  alertBody: { color: "#E17100", fontSize: 11, lineHeight: 16, marginTop: 2 },
  bodyText: { color: SALE.ink, fontSize: 12, lineHeight: 19 },
  bulletRow: { flexDirection: "row", gap: 9, marginTop: 9 },
  bullet: { width: 6, height: 6, borderRadius: 3, backgroundColor: SALE.gold, marginTop: 6 },
  fixedActions: { position: "absolute", left: 0, right: 0, bottom: 0, backgroundColor: SALE.white, borderTopWidth: 1, borderTopColor: SALE.border, paddingHorizontal: 19, paddingVertical: 15, flexDirection: "row", gap: 9 },
  fixedPrimary: { flex: 2, height: 41, borderRadius: 15, backgroundColor: SALE.charcoal, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 7 },
  fixedSecondary: { flex: 1, height: 41, borderRadius: 15, backgroundColor: SALE.pale, alignItems: "center", justifyContent: "center" },
  memberRow: { flexDirection: "row", gap: 11, alignItems: "center", marginTop: 11 },
  memberCopy: { flex: 1 },
  memberName: { color: SALE.ink, fontSize: 13 },
  memberRole: { color: SALE.muted, fontSize: 10, marginTop: 2 },
  availability: { color: "#009966", fontSize: 9 },
  fileRow: { flexDirection: "row", alignItems: "center", gap: 11, paddingVertical: 11, borderBottomWidth: 1, borderBottomColor: SALE.border },
  fileIcon: { width: 35, height: 35, borderRadius: 11, backgroundColor: SALE.pale, alignItems: "center", justifyContent: "center" },
  fileCopy: { flex: 1 },
  fileName: { color: SALE.ink, fontSize: 12, fontWeight: "500" },
  fileMeta: { color: SALE.muted, fontSize: 10, marginTop: 2 },
  messageArea: { padding: 19, gap: 10 },
  bubble: { maxWidth: "82%", borderRadius: 15, paddingHorizontal: 13, paddingVertical: 10 },
  bubbleOther: { alignSelf: "flex-start", backgroundColor: SALE.white, borderWidth: 1, borderColor: SALE.border },
  bubbleOwn: { alignSelf: "flex-end", backgroundColor: SALE.charcoal },
  bubbleText: { fontSize: 12, lineHeight: 18, color: SALE.ink },
  bubbleOwnText: { color: SALE.white },
  bubbleTime: { color: SALE.muted, fontSize: 9, marginTop: 4 },
  composer: { backgroundColor: SALE.white, borderTopWidth: 1, borderTopColor: SALE.border, paddingHorizontal: 12, paddingTop: 9, flexDirection: "row", alignItems: "center", gap: 8 },
  composerInput: { flex: 1, minHeight: 40, maxHeight: 90, borderRadius: 18, backgroundColor: SALE.pale, paddingHorizontal: 13, paddingVertical: 9, color: SALE.ink, fontSize: 13 },
  send: { width: 38, height: 38, borderRadius: 19, backgroundColor: SALE.charcoal, alignItems: "center", justifyContent: "center" },
  scheduleRow: { marginTop: 10 },
  scheduleMeta: { flexDirection: "row", alignItems: "center", gap: 7, marginTop: 8 },
  dashed: { borderWidth: 1, borderStyle: "dashed", borderColor: "rgba(60,51,48,.16)", backgroundColor: "rgba(245,242,237,.5)", alignItems: "center" },
  modalBackdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,.4)" },
  sheet: { width: "100%", maxWidth: 420, alignSelf: "center", backgroundColor: SALE.white, borderTopLeftRadius: 23, borderTopRightRadius: 23 },
  sheetHandle: { width: 38, height: 4, borderRadius: 2, backgroundColor: "rgba(60,51,48,.12)", alignSelf: "center", marginTop: 11, marginBottom: 4 },
  sheetHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 19, paddingVertical: 11, borderBottomWidth: 1, borderBottomColor: SALE.border },
  sheetTitle: { color: SALE.ink, fontFamily: "serif", fontSize: 16 },
  sheetBody: { paddingHorizontal: 19, paddingTop: 15, paddingBottom: 23, gap: 11 },
  sheetInput: { height: 40, borderRadius: 15, backgroundColor: SALE.pale, paddingHorizontal: 13, color: SALE.ink, fontSize: 13 },
  typeRow: { flexDirection: "row", gap: 8 },
  typeOption: { flex: 1, height: 34, borderRadius: 15, backgroundColor: SALE.pale, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: SALE.border },
  typeSelected: { backgroundColor: "#EEF2FF", borderColor: "#7C86FF" },
  dateRow: { flexDirection: "row", gap: 8 },
  dateField: { flex: 1, height: 40, borderRadius: 15, backgroundColor: SALE.pale, justifyContent: "center", paddingHorizontal: 10 },
  dateText: { color: SALE.muted, fontSize: 11 },
  profileHero: { backgroundColor: SALE.charcoal, paddingHorizontal: 19, paddingBottom: 20 },
  profileRow: { flexDirection: "row", gap: 13, alignItems: "center", marginTop: 17 },
  profileAvatar: { width: 55, height: 55, borderRadius: 28, backgroundColor: SALE.gold, alignItems: "center", justifyContent: "center" },
  profileName: { color: SALE.white, fontFamily: "serif", fontSize: 17 },
  profileRole: { color: "rgba(255,255,255,.5)", fontSize: 10, marginTop: 2 },
  settingRow: { minHeight: 54, flexDirection: "row", alignItems: "center", gap: 11, borderBottomWidth: 1, borderBottomColor: SALE.border },
  settingIcon: { width: 31, height: 31, borderRadius: 11, backgroundColor: SALE.pale, alignItems: "center", justifyContent: "center" },
  settingCopy: { flex: 1 },
  settingTitle: { color: SALE.ink, fontSize: 12 },
  settingSubtitle: { color: SALE.muted, fontSize: 10, marginTop: 2 },
  signOut: { flexDirection: "row", alignItems: "center", gap: 11, borderRadius: 15, backgroundColor: "#FFF5F5", borderWidth: 1, borderColor: "#FFE2E2", padding: 15 },
  signOutTitle: { color: SALE.red, fontSize: 12, fontWeight: "600" },
  centerMuted: { color: "rgba(122,111,104,.55)", fontSize: 10, textAlign: "center", marginTop: 12 },
});
